//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 06:42:47 PM CET 
//


package it.beniculturali.sas.catalogo.depositi;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.beniculturali.sas.catalogo.depositi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DDepositiDateEstremoRecente_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "date_estremo_recente");
    private final static QName _DDepositiFkVocValiditaDtrm_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "fk_voc_validita_dtrm");
    private final static QName _DDepositiFkVocSpecificaSerm_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "fk_voc_specifica_serm");
    private final static QName _DDepositiDateEstremoRemoto_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "date_estremo_remoto");
    private final static QName _DDepositiTextSecoloRe_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "text_secolo_re");
    private final static QName _DDepositiFkVocValiditaDtre_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "fk_voc_validita_dtre");
    private final static QName _DDepositiTextNoteData_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "text_note_data");
    private final static QName _DDepositiTextNote_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "text_note");
    private final static QName _DDepositiTextSecoloRm_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "text_secolo_rm");
    private final static QName _DDepositiFkVocSpecificaSere_QNAME = new QName("http://sas.beniculturali.it/catalogo/depositi", "fk_voc_specifica_sere");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.beniculturali.sas.catalogo.depositi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DDepositi.FkVocSpecificaSerm }
     * 
     */
    public DDepositi.FkVocSpecificaSerm createDDepositiFkVocSpecificaSerm() {
        return new DDepositi.FkVocSpecificaSerm();
    }

    /**
     * Create an instance of {@link DDepositi.FkVocValiditaDtre }
     * 
     */
    public DDepositi.FkVocValiditaDtre createDDepositiFkVocValiditaDtre() {
        return new DDepositi.FkVocValiditaDtre();
    }

    /**
     * Create an instance of {@link DDepositi }
     * 
     */
    public DDepositi createDDepositi() {
        return new DDepositi();
    }

    /**
     * Create an instance of {@link DDepositi.FkVocValiditaDtrm }
     * 
     */
    public DDepositi.FkVocValiditaDtrm createDDepositiFkVocValiditaDtrm() {
        return new DDepositi.FkVocValiditaDtrm();
    }

    /**
     * Create an instance of {@link DDepositi.FkVocTipoDeposito }
     * 
     */
    public DDepositi.FkVocTipoDeposito createDDepositiFkVocTipoDeposito() {
        return new DDepositi.FkVocTipoDeposito();
    }

    /**
     * Create an instance of {@link DDepositi.FkVocSpecificaSere }
     * 
     */
    public DDepositi.FkVocSpecificaSere createDDepositiFkVocSpecificaSere() {
        return new DDepositi.FkVocSpecificaSere();
    }

    /**
     * Create an instance of {@link DDepositi.FkFonte }
     * 
     */
    public DDepositi.FkFonte createDDepositiFkFonte() {
        return new DDepositi.FkFonte();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "date_estremo_recente", scope = DDepositi.class)
    public JAXBElement<XMLGregorianCalendar> createDDepositiDateEstremoRecente(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DDepositiDateEstremoRecente_QNAME, XMLGregorianCalendar.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DDepositi.FkVocValiditaDtrm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "fk_voc_validita_dtrm", scope = DDepositi.class)
    public JAXBElement<DDepositi.FkVocValiditaDtrm> createDDepositiFkVocValiditaDtrm(DDepositi.FkVocValiditaDtrm value) {
        return new JAXBElement<DDepositi.FkVocValiditaDtrm>(_DDepositiFkVocValiditaDtrm_QNAME, DDepositi.FkVocValiditaDtrm.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DDepositi.FkVocSpecificaSerm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "fk_voc_specifica_serm", scope = DDepositi.class)
    public JAXBElement<DDepositi.FkVocSpecificaSerm> createDDepositiFkVocSpecificaSerm(DDepositi.FkVocSpecificaSerm value) {
        return new JAXBElement<DDepositi.FkVocSpecificaSerm>(_DDepositiFkVocSpecificaSerm_QNAME, DDepositi.FkVocSpecificaSerm.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "date_estremo_remoto", scope = DDepositi.class)
    public JAXBElement<XMLGregorianCalendar> createDDepositiDateEstremoRemoto(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DDepositiDateEstremoRemoto_QNAME, XMLGregorianCalendar.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "text_secolo_re", scope = DDepositi.class)
    public JAXBElement<String> createDDepositiTextSecoloRe(String value) {
        return new JAXBElement<String>(_DDepositiTextSecoloRe_QNAME, String.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DDepositi.FkVocValiditaDtre }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "fk_voc_validita_dtre", scope = DDepositi.class)
    public JAXBElement<DDepositi.FkVocValiditaDtre> createDDepositiFkVocValiditaDtre(DDepositi.FkVocValiditaDtre value) {
        return new JAXBElement<DDepositi.FkVocValiditaDtre>(_DDepositiFkVocValiditaDtre_QNAME, DDepositi.FkVocValiditaDtre.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "text_note_data", scope = DDepositi.class)
    public JAXBElement<String> createDDepositiTextNoteData(String value) {
        return new JAXBElement<String>(_DDepositiTextNoteData_QNAME, String.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "text_note", scope = DDepositi.class)
    public JAXBElement<String> createDDepositiTextNote(String value) {
        return new JAXBElement<String>(_DDepositiTextNote_QNAME, String.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "text_secolo_rm", scope = DDepositi.class)
    public JAXBElement<String> createDDepositiTextSecoloRm(String value) {
        return new JAXBElement<String>(_DDepositiTextSecoloRm_QNAME, String.class, DDepositi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DDepositi.FkVocSpecificaSere }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/depositi", name = "fk_voc_specifica_sere", scope = DDepositi.class)
    public JAXBElement<DDepositi.FkVocSpecificaSere> createDDepositiFkVocSpecificaSere(DDepositi.FkVocSpecificaSere value) {
        return new JAXBElement<DDepositi.FkVocSpecificaSere>(_DDepositiFkVocSpecificaSere_QNAME, DDepositi.FkVocSpecificaSere.class, DDepositi.class, value);
    }

}
