//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 10:27:57 AM CET 
//


package it.beniculturali.sas.catalogo.elmctx;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.beniculturali.sas.catalogo.elmctx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DContestoStoricoIstFkVocSpecificaSerm_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "fk_voc_specifica_serm");
    private final static QName _DContestoStoricoIstDateEstremoRemoto_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "date_estremo_remoto");
    private final static QName _DContestoStoricoIstTextSecoloRe_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "text_secolo_re");
    private final static QName _DContestoStoricoIstDateEstremoRecente_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "date_estremo_recente");
    private final static QName _DContestoStoricoIstFkVocValiditaDtrm_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "fk_voc_validita_dtrm");
    private final static QName _DContestoStoricoIstFkVocSpecificaSere_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "fk_voc_specifica_sere");
    private final static QName _DContestoStoricoIstTextSecoloRm_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "text_secolo_rm");
    private final static QName _DContestoStoricoIstTextEstrCronoTestuali_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "text_estr_crono_testuali");
    private final static QName _DContestoStoricoIstTextNoteData_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "text_note_data");
    private final static QName _DContestoStoricoIstFkVocValiditaDtre_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "fk_voc_validita_dtre");
    private final static QName _DContestoStoricoIstDescrContesto_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "descr_contesto");
    private final static QName _DStrutturaAmministrativaTextDescrizione_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "text_descrizione");
    private final static QName _DAmbitoTerritorialeDescrAmbito_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "descr_ambito");
    private final static QName _DTipologiaDocumentariaTextDescrTipologiaDoc_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "text_descr_tipologia_doc");
    private final static QName _DProfiloStoricoIstDescrProfilo_QNAME = new QName("http://sas.beniculturali.it/catalogo/elmctx", "descr_profilo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.beniculturali.sas.catalogo.elmctx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DContestoStoricoIst }
     * 
     */
    public DContestoStoricoIst createDContestoStoricoIst() {
        return new DContestoStoricoIst();
    }

    /**
     * Create an instance of {@link DTipologiaDocumentaria.FkFonte }
     * 
     */
    public DTipologiaDocumentaria.FkFonte createDTipologiaDocumentariaFkFonte() {
        return new DTipologiaDocumentaria.FkFonte();
    }

    /**
     * Create an instance of {@link DTipologiaDocumentaria }
     * 
     */
    public DTipologiaDocumentaria createDTipologiaDocumentaria() {
        return new DTipologiaDocumentaria();
    }

    /**
     * Create an instance of {@link DAmbitoTerritoriale.FkFonte }
     * 
     */
    public DAmbitoTerritoriale.FkFonte createDAmbitoTerritorialeFkFonte() {
        return new DAmbitoTerritoriale.FkFonte();
    }

    /**
     * Create an instance of {@link DProfiloStoricoIst.FkFonte }
     * 
     */
    public DProfiloStoricoIst.FkFonte createDProfiloStoricoIstFkFonte() {
        return new DProfiloStoricoIst.FkFonte();
    }

    /**
     * Create an instance of {@link DProfiloStoricoIst.FkVocValiditaDtre }
     * 
     */
    public DProfiloStoricoIst.FkVocValiditaDtre createDProfiloStoricoIstFkVocValiditaDtre() {
        return new DProfiloStoricoIst.FkVocValiditaDtre();
    }

    /**
     * Create an instance of {@link DAmbitoTerritoriale.FkVocValiditaDtre }
     * 
     */
    public DAmbitoTerritoriale.FkVocValiditaDtre createDAmbitoTerritorialeFkVocValiditaDtre() {
        return new DAmbitoTerritoriale.FkVocValiditaDtre();
    }

    /**
     * Create an instance of {@link DAmbitoTerritoriale.FkVocValiditaDtrm }
     * 
     */
    public DAmbitoTerritoriale.FkVocValiditaDtrm createDAmbitoTerritorialeFkVocValiditaDtrm() {
        return new DAmbitoTerritoriale.FkVocValiditaDtrm();
    }

    /**
     * Create an instance of {@link DContestoStoricoIst.FkFonte }
     * 
     */
    public DContestoStoricoIst.FkFonte createDContestoStoricoIstFkFonte() {
        return new DContestoStoricoIst.FkFonte();
    }

    /**
     * Create an instance of {@link DProfiloStoricoIst.FkVocSpecificaSerm }
     * 
     */
    public DProfiloStoricoIst.FkVocSpecificaSerm createDProfiloStoricoIstFkVocSpecificaSerm() {
        return new DProfiloStoricoIst.FkVocSpecificaSerm();
    }

    /**
     * Create an instance of {@link DContestoStoricoIst.FkVocSpecificaSere }
     * 
     */
    public DContestoStoricoIst.FkVocSpecificaSere createDContestoStoricoIstFkVocSpecificaSere() {
        return new DContestoStoricoIst.FkVocSpecificaSere();
    }

    /**
     * Create an instance of {@link DProfiloStoricoIst }
     * 
     */
    public DProfiloStoricoIst createDProfiloStoricoIst() {
        return new DProfiloStoricoIst();
    }

    /**
     * Create an instance of {@link DAmbitoTerritoriale.FkVocSpecificaSerm }
     * 
     */
    public DAmbitoTerritoriale.FkVocSpecificaSerm createDAmbitoTerritorialeFkVocSpecificaSerm() {
        return new DAmbitoTerritoriale.FkVocSpecificaSerm();
    }

    /**
     * Create an instance of {@link DContestoStoricoIst.FkVocValiditaDtre }
     * 
     */
    public DContestoStoricoIst.FkVocValiditaDtre createDContestoStoricoIstFkVocValiditaDtre() {
        return new DContestoStoricoIst.FkVocValiditaDtre();
    }

    /**
     * Create an instance of {@link DContestoStoricoIst.FkVocSpecificaSerm }
     * 
     */
    public DContestoStoricoIst.FkVocSpecificaSerm createDContestoStoricoIstFkVocSpecificaSerm() {
        return new DContestoStoricoIst.FkVocSpecificaSerm();
    }

    /**
     * Create an instance of {@link DProfiloStoricoIst.FkVocSpecificaSere }
     * 
     */
    public DProfiloStoricoIst.FkVocSpecificaSere createDProfiloStoricoIstFkVocSpecificaSere() {
        return new DProfiloStoricoIst.FkVocSpecificaSere();
    }

    /**
     * Create an instance of {@link DStrutturaAmministrativa }
     * 
     */
    public DStrutturaAmministrativa createDStrutturaAmministrativa() {
        return new DStrutturaAmministrativa();
    }

    /**
     * Create an instance of {@link DAmbitoTerritoriale }
     * 
     */
    public DAmbitoTerritoriale createDAmbitoTerritoriale() {
        return new DAmbitoTerritoriale();
    }

    /**
     * Create an instance of {@link DStrutturaAmministrativa.FkFonte }
     * 
     */
    public DStrutturaAmministrativa.FkFonte createDStrutturaAmministrativaFkFonte() {
        return new DStrutturaAmministrativa.FkFonte();
    }

    /**
     * Create an instance of {@link DAmbitoTerritoriale.FkVocSpecificaSere }
     * 
     */
    public DAmbitoTerritoriale.FkVocSpecificaSere createDAmbitoTerritorialeFkVocSpecificaSere() {
        return new DAmbitoTerritoriale.FkVocSpecificaSere();
    }

    /**
     * Create an instance of {@link DContestoStoricoIst.FkVocValiditaDtrm }
     * 
     */
    public DContestoStoricoIst.FkVocValiditaDtrm createDContestoStoricoIstFkVocValiditaDtrm() {
        return new DContestoStoricoIst.FkVocValiditaDtrm();
    }

    /**
     * Create an instance of {@link DProfiloStoricoIst.FkVocValiditaDtrm }
     * 
     */
    public DProfiloStoricoIst.FkVocValiditaDtrm createDProfiloStoricoIstFkVocValiditaDtrm() {
        return new DProfiloStoricoIst.FkVocValiditaDtrm();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DContestoStoricoIst.FkVocSpecificaSerm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_specifica_serm", scope = DContestoStoricoIst.class)
    public JAXBElement<DContestoStoricoIst.FkVocSpecificaSerm> createDContestoStoricoIstFkVocSpecificaSerm(DContestoStoricoIst.FkVocSpecificaSerm value) {
        return new JAXBElement<DContestoStoricoIst.FkVocSpecificaSerm>(_DContestoStoricoIstFkVocSpecificaSerm_QNAME, DContestoStoricoIst.FkVocSpecificaSerm.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "date_estremo_remoto", scope = DContestoStoricoIst.class)
    public JAXBElement<XMLGregorianCalendar> createDContestoStoricoIstDateEstremoRemoto(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DContestoStoricoIstDateEstremoRemoto_QNAME, XMLGregorianCalendar.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_secolo_re", scope = DContestoStoricoIst.class)
    public JAXBElement<String> createDContestoStoricoIstTextSecoloRe(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextSecoloRe_QNAME, String.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "date_estremo_recente", scope = DContestoStoricoIst.class)
    public JAXBElement<XMLGregorianCalendar> createDContestoStoricoIstDateEstremoRecente(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DContestoStoricoIstDateEstremoRecente_QNAME, XMLGregorianCalendar.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DContestoStoricoIst.FkVocValiditaDtrm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_validita_dtrm", scope = DContestoStoricoIst.class)
    public JAXBElement<DContestoStoricoIst.FkVocValiditaDtrm> createDContestoStoricoIstFkVocValiditaDtrm(DContestoStoricoIst.FkVocValiditaDtrm value) {
        return new JAXBElement<DContestoStoricoIst.FkVocValiditaDtrm>(_DContestoStoricoIstFkVocValiditaDtrm_QNAME, DContestoStoricoIst.FkVocValiditaDtrm.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DContestoStoricoIst.FkVocSpecificaSere }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_specifica_sere", scope = DContestoStoricoIst.class)
    public JAXBElement<DContestoStoricoIst.FkVocSpecificaSere> createDContestoStoricoIstFkVocSpecificaSere(DContestoStoricoIst.FkVocSpecificaSere value) {
        return new JAXBElement<DContestoStoricoIst.FkVocSpecificaSere>(_DContestoStoricoIstFkVocSpecificaSere_QNAME, DContestoStoricoIst.FkVocSpecificaSere.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_secolo_rm", scope = DContestoStoricoIst.class)
    public JAXBElement<String> createDContestoStoricoIstTextSecoloRm(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextSecoloRm_QNAME, String.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_estr_crono_testuali", scope = DContestoStoricoIst.class)
    public JAXBElement<String> createDContestoStoricoIstTextEstrCronoTestuali(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextEstrCronoTestuali_QNAME, String.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_note_data", scope = DContestoStoricoIst.class)
    public JAXBElement<String> createDContestoStoricoIstTextNoteData(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextNoteData_QNAME, String.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DContestoStoricoIst.FkVocValiditaDtre }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_validita_dtre", scope = DContestoStoricoIst.class)
    public JAXBElement<DContestoStoricoIst.FkVocValiditaDtre> createDContestoStoricoIstFkVocValiditaDtre(DContestoStoricoIst.FkVocValiditaDtre value) {
        return new JAXBElement<DContestoStoricoIst.FkVocValiditaDtre>(_DContestoStoricoIstFkVocValiditaDtre_QNAME, DContestoStoricoIst.FkVocValiditaDtre.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "descr_contesto", scope = DContestoStoricoIst.class)
    public JAXBElement<String> createDContestoStoricoIstDescrContesto(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstDescrContesto_QNAME, String.class, DContestoStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_descrizione", scope = DStrutturaAmministrativa.class)
    public JAXBElement<String> createDStrutturaAmministrativaTextDescrizione(String value) {
        return new JAXBElement<String>(_DStrutturaAmministrativaTextDescrizione_QNAME, String.class, DStrutturaAmministrativa.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DAmbitoTerritoriale.FkVocSpecificaSerm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_specifica_serm", scope = DAmbitoTerritoriale.class)
    public JAXBElement<DAmbitoTerritoriale.FkVocSpecificaSerm> createDAmbitoTerritorialeFkVocSpecificaSerm(DAmbitoTerritoriale.FkVocSpecificaSerm value) {
        return new JAXBElement<DAmbitoTerritoriale.FkVocSpecificaSerm>(_DContestoStoricoIstFkVocSpecificaSerm_QNAME, DAmbitoTerritoriale.FkVocSpecificaSerm.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "date_estremo_remoto", scope = DAmbitoTerritoriale.class)
    public JAXBElement<XMLGregorianCalendar> createDAmbitoTerritorialeDateEstremoRemoto(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DContestoStoricoIstDateEstremoRemoto_QNAME, XMLGregorianCalendar.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "descr_ambito", scope = DAmbitoTerritoriale.class)
    public JAXBElement<String> createDAmbitoTerritorialeDescrAmbito(String value) {
        return new JAXBElement<String>(_DAmbitoTerritorialeDescrAmbito_QNAME, String.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_secolo_re", scope = DAmbitoTerritoriale.class)
    public JAXBElement<String> createDAmbitoTerritorialeTextSecoloRe(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextSecoloRe_QNAME, String.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "date_estremo_recente", scope = DAmbitoTerritoriale.class)
    public JAXBElement<XMLGregorianCalendar> createDAmbitoTerritorialeDateEstremoRecente(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DContestoStoricoIstDateEstremoRecente_QNAME, XMLGregorianCalendar.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DAmbitoTerritoriale.FkVocValiditaDtrm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_validita_dtrm", scope = DAmbitoTerritoriale.class)
    public JAXBElement<DAmbitoTerritoriale.FkVocValiditaDtrm> createDAmbitoTerritorialeFkVocValiditaDtrm(DAmbitoTerritoriale.FkVocValiditaDtrm value) {
        return new JAXBElement<DAmbitoTerritoriale.FkVocValiditaDtrm>(_DContestoStoricoIstFkVocValiditaDtrm_QNAME, DAmbitoTerritoriale.FkVocValiditaDtrm.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DAmbitoTerritoriale.FkVocSpecificaSere }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_specifica_sere", scope = DAmbitoTerritoriale.class)
    public JAXBElement<DAmbitoTerritoriale.FkVocSpecificaSere> createDAmbitoTerritorialeFkVocSpecificaSere(DAmbitoTerritoriale.FkVocSpecificaSere value) {
        return new JAXBElement<DAmbitoTerritoriale.FkVocSpecificaSere>(_DContestoStoricoIstFkVocSpecificaSere_QNAME, DAmbitoTerritoriale.FkVocSpecificaSere.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_secolo_rm", scope = DAmbitoTerritoriale.class)
    public JAXBElement<String> createDAmbitoTerritorialeTextSecoloRm(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextSecoloRm_QNAME, String.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_estr_crono_testuali", scope = DAmbitoTerritoriale.class)
    public JAXBElement<String> createDAmbitoTerritorialeTextEstrCronoTestuali(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextEstrCronoTestuali_QNAME, String.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_note_data", scope = DAmbitoTerritoriale.class)
    public JAXBElement<String> createDAmbitoTerritorialeTextNoteData(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextNoteData_QNAME, String.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DAmbitoTerritoriale.FkVocValiditaDtre }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_validita_dtre", scope = DAmbitoTerritoriale.class)
    public JAXBElement<DAmbitoTerritoriale.FkVocValiditaDtre> createDAmbitoTerritorialeFkVocValiditaDtre(DAmbitoTerritoriale.FkVocValiditaDtre value) {
        return new JAXBElement<DAmbitoTerritoriale.FkVocValiditaDtre>(_DContestoStoricoIstFkVocValiditaDtre_QNAME, DAmbitoTerritoriale.FkVocValiditaDtre.class, DAmbitoTerritoriale.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_descr_tipologia_doc", scope = DTipologiaDocumentaria.class)
    public JAXBElement<String> createDTipologiaDocumentariaTextDescrTipologiaDoc(String value) {
        return new JAXBElement<String>(_DTipologiaDocumentariaTextDescrTipologiaDoc_QNAME, String.class, DTipologiaDocumentaria.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DProfiloStoricoIst.FkVocSpecificaSerm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_specifica_serm", scope = DProfiloStoricoIst.class)
    public JAXBElement<DProfiloStoricoIst.FkVocSpecificaSerm> createDProfiloStoricoIstFkVocSpecificaSerm(DProfiloStoricoIst.FkVocSpecificaSerm value) {
        return new JAXBElement<DProfiloStoricoIst.FkVocSpecificaSerm>(_DContestoStoricoIstFkVocSpecificaSerm_QNAME, DProfiloStoricoIst.FkVocSpecificaSerm.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "date_estremo_remoto", scope = DProfiloStoricoIst.class)
    public JAXBElement<XMLGregorianCalendar> createDProfiloStoricoIstDateEstremoRemoto(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DContestoStoricoIstDateEstremoRemoto_QNAME, XMLGregorianCalendar.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_secolo_re", scope = DProfiloStoricoIst.class)
    public JAXBElement<String> createDProfiloStoricoIstTextSecoloRe(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextSecoloRe_QNAME, String.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "date_estremo_recente", scope = DProfiloStoricoIst.class)
    public JAXBElement<XMLGregorianCalendar> createDProfiloStoricoIstDateEstremoRecente(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DContestoStoricoIstDateEstremoRecente_QNAME, XMLGregorianCalendar.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "descr_profilo", scope = DProfiloStoricoIst.class)
    public JAXBElement<String> createDProfiloStoricoIstDescrProfilo(String value) {
        return new JAXBElement<String>(_DProfiloStoricoIstDescrProfilo_QNAME, String.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DProfiloStoricoIst.FkVocValiditaDtrm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_validita_dtrm", scope = DProfiloStoricoIst.class)
    public JAXBElement<DProfiloStoricoIst.FkVocValiditaDtrm> createDProfiloStoricoIstFkVocValiditaDtrm(DProfiloStoricoIst.FkVocValiditaDtrm value) {
        return new JAXBElement<DProfiloStoricoIst.FkVocValiditaDtrm>(_DContestoStoricoIstFkVocValiditaDtrm_QNAME, DProfiloStoricoIst.FkVocValiditaDtrm.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DProfiloStoricoIst.FkVocSpecificaSere }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_specifica_sere", scope = DProfiloStoricoIst.class)
    public JAXBElement<DProfiloStoricoIst.FkVocSpecificaSere> createDProfiloStoricoIstFkVocSpecificaSere(DProfiloStoricoIst.FkVocSpecificaSere value) {
        return new JAXBElement<DProfiloStoricoIst.FkVocSpecificaSere>(_DContestoStoricoIstFkVocSpecificaSere_QNAME, DProfiloStoricoIst.FkVocSpecificaSere.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_secolo_rm", scope = DProfiloStoricoIst.class)
    public JAXBElement<String> createDProfiloStoricoIstTextSecoloRm(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextSecoloRm_QNAME, String.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_estr_crono_testuali", scope = DProfiloStoricoIst.class)
    public JAXBElement<String> createDProfiloStoricoIstTextEstrCronoTestuali(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextEstrCronoTestuali_QNAME, String.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "text_note_data", scope = DProfiloStoricoIst.class)
    public JAXBElement<String> createDProfiloStoricoIstTextNoteData(String value) {
        return new JAXBElement<String>(_DContestoStoricoIstTextNoteData_QNAME, String.class, DProfiloStoricoIst.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DProfiloStoricoIst.FkVocValiditaDtre }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sas.beniculturali.it/catalogo/elmctx", name = "fk_voc_validita_dtre", scope = DProfiloStoricoIst.class)
    public JAXBElement<DProfiloStoricoIst.FkVocValiditaDtre> createDProfiloStoricoIstFkVocValiditaDtre(DProfiloStoricoIst.FkVocValiditaDtre value) {
        return new JAXBElement<DProfiloStoricoIst.FkVocValiditaDtre>(_DContestoStoricoIstFkVocValiditaDtre_QNAME, DProfiloStoricoIst.FkVocValiditaDtre.class, DProfiloStoricoIst.class, value);
    }

}
