//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.27 at 02:03:47 PM CET 
//


package it.beniculturali.sas.catalogo.relazioni;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_risorse_bibl"/>
 *         &lt;choice>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_sogc"/>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_sogp"/>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_comparc"/>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_ambterr"/>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_csi"/>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_profist"/>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_tipologiadoc"/>
 *           &lt;element ref="{http://sas.beniculturali.it/catalogo/relazioni}codi_provenienza_strumenti"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codiProvenienzaRisorseBibl",
    "codiProvenienzaSogc",
    "codiProvenienzaSogp",
    "codiProvenienzaComparc",
    "codiProvenienzaAmbterr",
    "codiProvenienzaCsi",
    "codiProvenienzaProfist",
    "codiProvenienzaTipologiadoc",
    "codiProvenienzaStrumenti"
})
@XmlRootElement(name = "d_rel_risorse_bibl")
public class DRelRisorseBibl {

    @XmlElement(name = "codi_provenienza_risorse_bibl", required = true)
    protected String codiProvenienzaRisorseBibl;
    @XmlElement(name = "codi_provenienza_sogc")
    protected String codiProvenienzaSogc;
    @XmlElement(name = "codi_provenienza_sogp")
    protected String codiProvenienzaSogp;
    @XmlElement(name = "codi_provenienza_comparc")
    protected String codiProvenienzaComparc;
    @XmlElement(name = "codi_provenienza_ambterr")
    protected String codiProvenienzaAmbterr;
    @XmlElement(name = "codi_provenienza_csi")
    protected String codiProvenienzaCsi;
    @XmlElement(name = "codi_provenienza_profist")
    protected String codiProvenienzaProfist;
    @XmlElement(name = "codi_provenienza_tipologiadoc")
    protected String codiProvenienzaTipologiadoc;
    @XmlElement(name = "codi_provenienza_strumenti")
    protected String codiProvenienzaStrumenti;

    /**
     * Gets the value of the codiProvenienzaRisorseBibl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaRisorseBibl() {
        return codiProvenienzaRisorseBibl;
    }

    /**
     * Sets the value of the codiProvenienzaRisorseBibl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaRisorseBibl(String value) {
        this.codiProvenienzaRisorseBibl = value;
    }

    /**
     * Gets the value of the codiProvenienzaSogc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaSogc() {
        return codiProvenienzaSogc;
    }

    /**
     * Sets the value of the codiProvenienzaSogc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaSogc(String value) {
        this.codiProvenienzaSogc = value;
    }

    /**
     * Gets the value of the codiProvenienzaSogp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaSogp() {
        return codiProvenienzaSogp;
    }

    /**
     * Sets the value of the codiProvenienzaSogp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaSogp(String value) {
        this.codiProvenienzaSogp = value;
    }

    /**
     * Gets the value of the codiProvenienzaComparc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaComparc() {
        return codiProvenienzaComparc;
    }

    /**
     * Sets the value of the codiProvenienzaComparc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaComparc(String value) {
        this.codiProvenienzaComparc = value;
    }

    /**
     * Gets the value of the codiProvenienzaAmbterr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaAmbterr() {
        return codiProvenienzaAmbterr;
    }

    /**
     * Sets the value of the codiProvenienzaAmbterr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaAmbterr(String value) {
        this.codiProvenienzaAmbterr = value;
    }

    /**
     * Gets the value of the codiProvenienzaCsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaCsi() {
        return codiProvenienzaCsi;
    }

    /**
     * Sets the value of the codiProvenienzaCsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaCsi(String value) {
        this.codiProvenienzaCsi = value;
    }

    /**
     * Gets the value of the codiProvenienzaProfist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaProfist() {
        return codiProvenienzaProfist;
    }

    /**
     * Sets the value of the codiProvenienzaProfist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaProfist(String value) {
        this.codiProvenienzaProfist = value;
    }

    /**
     * Gets the value of the codiProvenienzaTipologiadoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaTipologiadoc() {
        return codiProvenienzaTipologiadoc;
    }

    /**
     * Sets the value of the codiProvenienzaTipologiadoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaTipologiadoc(String value) {
        this.codiProvenienzaTipologiadoc = value;
    }

    /**
     * Gets the value of the codiProvenienzaStrumenti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaStrumenti() {
        return codiProvenienzaStrumenti;
    }

    /**
     * Sets the value of the codiProvenienzaStrumenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaStrumenti(String value) {
        this.codiProvenienzaStrumenti = value;
    }

}
