//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 11:10:43 AM CET 
//


package it.beniculturali.sas.catalogo.sogp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.beniculturali.sas.catalogo.vocabolari_sogp.DVocFontiInformative;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text_note" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_fonti_informative" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogp}d_voc_fonti_informative"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="codi_provenienza_bibliografia">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="256"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textNote",
    "fkVocFontiInformative",
    "codiProvenienzaBibliografia"
})
@XmlRootElement(name = "d_fonti_informative")
public class DFontiInformative {

    @XmlElementRef(name = "text_note", namespace = "http://sas.beniculturali.it/catalogo/sogp", type = JAXBElement.class, required = false)
    protected JAXBElement<String> textNote;
    @XmlElementRef(name = "fk_voc_fonti_informative", namespace = "http://sas.beniculturali.it/catalogo/sogp", type = JAXBElement.class, required = false)
    protected JAXBElement<DFontiInformative.FkVocFontiInformative> fkVocFontiInformative;
    @XmlElement(name = "codi_provenienza_bibliografia", required = true)
    protected String codiProvenienzaBibliografia;

    /**
     * Gets the value of the textNote property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextNote() {
        return textNote;
    }

    /**
     * Sets the value of the textNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextNote(JAXBElement<String> value) {
        this.textNote = value;
    }

    /**
     * Gets the value of the fkVocFontiInformative property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DFontiInformative.FkVocFontiInformative }{@code >}
     *     
     */
    public JAXBElement<DFontiInformative.FkVocFontiInformative> getFkVocFontiInformative() {
        return fkVocFontiInformative;
    }

    /**
     * Sets the value of the fkVocFontiInformative property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DFontiInformative.FkVocFontiInformative }{@code >}
     *     
     */
    public void setFkVocFontiInformative(JAXBElement<DFontiInformative.FkVocFontiInformative> value) {
        this.fkVocFontiInformative = value;
    }

    /**
     * Gets the value of the codiProvenienzaBibliografia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienzaBibliografia() {
        return codiProvenienzaBibliografia;
    }

    /**
     * Sets the value of the codiProvenienzaBibliografia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienzaBibliografia(String value) {
        this.codiProvenienzaBibliografia = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogp}d_voc_fonti_informative"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocFontiInformative"
    })
    public static class FkVocFontiInformative {

        @XmlElement(name = "d_voc_fonti_informative", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-sogp")
        protected DVocFontiInformative dVocFontiInformative;

        /**
         * Gets the value of the dVocFontiInformative property.
         * 
         * @return
         *     possible object is
         *     {@link DVocFontiInformative }
         *     
         */
        public DVocFontiInformative getDVocFontiInformative() {
            return dVocFontiInformative;
        }

        /**
         * Sets the value of the dVocFontiInformative property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocFontiInformative }
         *     
         */
        public void setDVocFontiInformative(DVocFontiInformative value) {
            this.dVocFontiInformative = value;
        }

    }

}
