//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 04:50:28 PM CET 
//


package it.beniculturali.sas.catalogo.fonti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="group_name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="ARCHIVI_DI_STATO"/>
 *               &lt;enumeration value="CACT"/>
 *               &lt;enumeration value="DIP-ABC"/>
 *               &lt;enumeration value="GGASI"/>
 *               &lt;enumeration value="IT-ER-IBC"/>
 *               &lt;enumeration value="ITASAG"/>
 *               &lt;enumeration value="ITASAL"/>
 *               &lt;enumeration value="ITASAN"/>
 *               &lt;enumeration value="ITASBG"/>
 *               &lt;enumeration value="ITASCT"/>
 *               &lt;enumeration value="ITASCT_SEZ_CALTAGIRONE"/>
 *               &lt;enumeration value="ITASLT"/>
 *               &lt;enumeration value="ITASNA"/>
 *               &lt;enumeration value="ITASPA"/>
 *               &lt;enumeration value="ITASRI"/>
 *               &lt;enumeration value="ITASSI"/>
 *               &lt;enumeration value="ITASVT"/>
 *               &lt;enumeration value="ITSASFABRI"/>
 *               &lt;enumeration value="PRCT"/>
 *               &lt;enumeration value="PREPCT"/>
 *               &lt;enumeration value="REDAZIONE_CENTRALE_SAS"/>
 *               &lt;enumeration value="SEZIONE_DISTACCATA_DI_SCIACCA"/>
 *               &lt;enumeration value="SIAS"/>
 *               &lt;enumeration value="SIASFI"/>
 *               &lt;enumeration value="SIUSA"/>
 *               &lt;enumeration value="SOPRINTENDENZA_ABRUZZO"/>
 *               &lt;enumeration value="SOPRINTENDENZA_BASILICATA"/>
 *               &lt;enumeration value="SOPRINTENDENZA_CALABRIA"/>
 *               &lt;enumeration value="SOPRINTENDENZE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupName"
})
@XmlRootElement(name = "prof_group")
public class ProfGroup {

    @XmlElement(name = "group_name", required = true)
    protected String groupName;

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

}
