//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.27 at 02:03:47 PM CET 
//


package it.beniculturali.sas.catalogo.sogc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import it.beniculturali.sas.catalogo.commons.DCompilatore;
import it.beniculturali.sas.catalogo.commons.DContatti;
import it.beniculturali.sas.catalogo.commons.DLocalizzazione;
import it.beniculturali.sas.catalogo.commons.DSogcStatoLocali;
import it.beniculturali.sas.catalogo.commons.DUrl;
import it.beniculturali.sas.catalogo.fonti.ProfGroup;
import it.beniculturali.sas.catalogo.vocabolari_sogc.DVocNaturagiuridica;
import it.beniculturali.sas.catalogo.vocabolari_sogc.DVocTipoSogc;
import it.beniculturali.sas.catalogo.vocabolari_trasv.DVocSpecificaSecoli;
import it.beniculturali.sas.catalogo.vocabolari_trasv.DVocValiditaDate;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codi_provenienza">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="256"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_denominazione">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_tipo_sogc">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogc}d_voc_tipo_sogc"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="flag_ammne_attiva_tf">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}boolean">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fk_fonte">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/fonti}prof_group"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="codi_isil" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_nazione_isad" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_codice_isad" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_sigla_isad" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_acronimo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_den_uniformata" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_naturagiuridica" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogc}d_voc_naturagiuridica"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="text_estr_crono_testuali">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="date_estremo_remoto" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *               &lt;minInclusive value="-4713-01-01"/>
 *               &lt;maxInclusive value="5874897-12-31"/>
 *               &lt;pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_secolo_rm" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="I"/>
 *               &lt;enumeration value="II"/>
 *               &lt;enumeration value="III"/>
 *               &lt;enumeration value="IV"/>
 *               &lt;enumeration value="V"/>
 *               &lt;enumeration value="VI"/>
 *               &lt;enumeration value="VII"/>
 *               &lt;enumeration value="VIII"/>
 *               &lt;enumeration value="IX"/>
 *               &lt;enumeration value="X"/>
 *               &lt;enumeration value="XI"/>
 *               &lt;enumeration value="XII"/>
 *               &lt;enumeration value="XIII"/>
 *               &lt;enumeration value="XIV"/>
 *               &lt;enumeration value="XV"/>
 *               &lt;enumeration value="XVI"/>
 *               &lt;enumeration value="XVII"/>
 *               &lt;enumeration value="XVIII"/>
 *               &lt;enumeration value="XIX"/>
 *               &lt;enumeration value="XX"/>
 *               &lt;enumeration value="XXI"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_validita_dtrm" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_validita_date"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_specifica_serm" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_specifica_secoli"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="date_estremo_recente" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *               &lt;minInclusive value="-4713-01-01"/>
 *               &lt;maxInclusive value="5874897-12-31"/>
 *               &lt;pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_secolo_re" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="I"/>
 *               &lt;enumeration value="II"/>
 *               &lt;enumeration value="III"/>
 *               &lt;enumeration value="IV"/>
 *               &lt;enumeration value="V"/>
 *               &lt;enumeration value="VI"/>
 *               &lt;enumeration value="VII"/>
 *               &lt;enumeration value="VIII"/>
 *               &lt;enumeration value="IX"/>
 *               &lt;enumeration value="X"/>
 *               &lt;enumeration value="XI"/>
 *               &lt;enumeration value="XII"/>
 *               &lt;enumeration value="XIII"/>
 *               &lt;enumeration value="XIV"/>
 *               &lt;enumeration value="XV"/>
 *               &lt;enumeration value="XVI"/>
 *               &lt;enumeration value="XVII"/>
 *               &lt;enumeration value="XVIII"/>
 *               &lt;enumeration value="XIX"/>
 *               &lt;enumeration value="XX"/>
 *               &lt;enumeration value="XXI"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_validita_dtre" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_validita_date"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_specifica_sere" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_specifica_secoli"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="text_note_data" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/sogc}d_sogc_den_parallela" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/sogc}d_sogc_altreden" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/commons}d_sogc_stato_locali" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/commons}d_localizzazione" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="text_circ_ecclesiastica" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/commons}d_contatti" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="text_cenni_storici_isti" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_contesto_territoriale_cult" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_mandato_fonti_normative" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_struttura_amministrativa" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_politiche_gestione_doc" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_edifici" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_patrimonio_archivistico" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_strumenti_ricerca" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/commons}d_url" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="codi_san" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_ist_resp" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_norme_convenzioni" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_grado_elaborazione" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_livello_completezza" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_fonti_informative" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/commons}d_compilatore" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="text_lingua_scrittura" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2147483647"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codiProvenienza",
    "textDenominazione",
    "fkVocTipoSogc",
    "flagAmmneAttivaTf",
    "fkFonte",
    "codiIsil",
    "textNazioneIsad",
    "textCodiceIsad",
    "textSiglaIsad",
    "textAcronimo",
    "textDenUniformata",
    "fkVocNaturagiuridica",
    "textEstrCronoTestuali",
    "dateEstremoRemoto",
    "textSecoloRm",
    "fkVocValiditaDtrm",
    "fkVocSpecificaSerm",
    "dateEstremoRecente",
    "textSecoloRe",
    "fkVocValiditaDtre",
    "fkVocSpecificaSere",
    "textNoteData",
    "dSogcDenParallela",
    "dSogcAltreden",
    "dSogcStatoLocali",
    "dLocalizzazione",
    "textCircEcclesiastica",
    "dContatti",
    "textCenniStoriciIsti",
    "textContestoTerritorialeCult",
    "textMandatoFontiNormative",
    "textStrutturaAmministrativa",
    "textPoliticheGestioneDoc",
    "textEdifici",
    "textPatrimonioArchivistico",
    "textStrumentiRicerca",
    "dUrl",
    "codiSan",
    "textIstResp",
    "textNormeConvenzioni",
    "textGradoElaborazione",
    "textLivelloCompletezza",
    "textFontiInformative",
    "dCompilatore",
    "textLinguaScrittura"
})
@XmlRootElement(name = "d_sogc")
public class DSogc {

    @XmlElement(name = "codi_provenienza", required = true)
    protected String codiProvenienza;
    @XmlElement(name = "text_denominazione", required = true)
    protected String textDenominazione;
    @XmlElement(name = "fk_voc_tipo_sogc", required = true, nillable = true)
    protected DSogc.FkVocTipoSogc fkVocTipoSogc;
    @XmlElement(name = "flag_ammne_attiva_tf", required = true, type = Boolean.class, nillable = true)
    protected Boolean flagAmmneAttivaTf;
    @XmlElement(name = "fk_fonte", required = true)
    protected DSogc.FkFonte fkFonte;
    @XmlElementRef(name = "codi_isil", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> codiIsil;
    @XmlElementRef(name = "text_nazione_isad", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textNazioneIsad;
    @XmlElementRef(name = "text_codice_isad", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textCodiceIsad;
    @XmlElementRef(name = "text_sigla_isad", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textSiglaIsad;
    @XmlElementRef(name = "text_acronimo", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textAcronimo;
    @XmlElementRef(name = "text_den_uniformata", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textDenUniformata;
    @XmlElementRef(name = "fk_voc_naturagiuridica", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<DSogc.FkVocNaturagiuridica> fkVocNaturagiuridica;
    @XmlElement(name = "text_estr_crono_testuali", required = true)
    protected String textEstrCronoTestuali;
    @XmlElementRef(name = "date_estremo_remoto", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> dateEstremoRemoto;
    @XmlElementRef(name = "text_secolo_rm", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textSecoloRm;
    @XmlElementRef(name = "fk_voc_validita_dtrm", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<DSogc.FkVocValiditaDtrm> fkVocValiditaDtrm;
    @XmlElementRef(name = "fk_voc_specifica_serm", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<DSogc.FkVocSpecificaSerm> fkVocSpecificaSerm;
    @XmlElementRef(name = "date_estremo_recente", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> dateEstremoRecente;
    @XmlElementRef(name = "text_secolo_re", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textSecoloRe;
    @XmlElementRef(name = "fk_voc_validita_dtre", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<DSogc.FkVocValiditaDtre> fkVocValiditaDtre;
    @XmlElementRef(name = "fk_voc_specifica_sere", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<DSogc.FkVocSpecificaSere> fkVocSpecificaSere;
    @XmlElementRef(name = "text_note_data", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textNoteData;
    @XmlElement(name = "d_sogc_den_parallela")
    protected List<DSogcDenParallela> dSogcDenParallela;
    @XmlElement(name = "d_sogc_altreden")
    protected List<DSogcAltreden> dSogcAltreden;
    @XmlElement(name = "d_sogc_stato_locali", namespace = "http://sas.beniculturali.it/catalogo/commons")
    protected List<DSogcStatoLocali> dSogcStatoLocali;
    @XmlElement(name = "d_localizzazione", namespace = "http://sas.beniculturali.it/catalogo/commons")
    protected List<DLocalizzazione> dLocalizzazione;
    @XmlElementRef(name = "text_circ_ecclesiastica", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textCircEcclesiastica;
    @XmlElement(name = "d_contatti", namespace = "http://sas.beniculturali.it/catalogo/commons")
    protected List<DContatti> dContatti;
    @XmlElementRef(name = "text_cenni_storici_isti", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textCenniStoriciIsti;
    @XmlElementRef(name = "text_contesto_territoriale_cult", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textContestoTerritorialeCult;
    @XmlElementRef(name = "text_mandato_fonti_normative", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textMandatoFontiNormative;
    @XmlElementRef(name = "text_struttura_amministrativa", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textStrutturaAmministrativa;
    @XmlElementRef(name = "text_politiche_gestione_doc", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textPoliticheGestioneDoc;
    @XmlElementRef(name = "text_edifici", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textEdifici;
    @XmlElementRef(name = "text_patrimonio_archivistico", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textPatrimonioArchivistico;
    @XmlElementRef(name = "text_strumenti_ricerca", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textStrumentiRicerca;
    @XmlElement(name = "d_url", namespace = "http://sas.beniculturali.it/catalogo/commons")
    protected List<DUrl> dUrl;
    @XmlElementRef(name = "codi_san", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> codiSan;
    @XmlElementRef(name = "text_ist_resp", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textIstResp;
    @XmlElementRef(name = "text_norme_convenzioni", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textNormeConvenzioni;
    @XmlElementRef(name = "text_grado_elaborazione", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textGradoElaborazione;
    @XmlElementRef(name = "text_livello_completezza", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textLivelloCompletezza;
    @XmlElementRef(name = "text_fonti_informative", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textFontiInformative;
    @XmlElement(name = "d_compilatore", namespace = "http://sas.beniculturali.it/catalogo/commons")
    protected List<DCompilatore> dCompilatore;
    @XmlElementRef(name = "text_lingua_scrittura", namespace = "http://sas.beniculturali.it/catalogo/sogc", type = JAXBElement.class)
    protected JAXBElement<String> textLinguaScrittura;

    /**
     * Gets the value of the codiProvenienza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienza() {
        return codiProvenienza;
    }

    /**
     * Sets the value of the codiProvenienza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienza(String value) {
        this.codiProvenienza = value;
    }

    /**
     * Gets the value of the textDenominazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDenominazione() {
        return textDenominazione;
    }

    /**
     * Sets the value of the textDenominazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDenominazione(String value) {
        this.textDenominazione = value;
    }

    /**
     * Gets the value of the fkVocTipoSogc property.
     * 
     * @return
     *     possible object is
     *     {@link DSogc.FkVocTipoSogc }
     *     
     */
    public DSogc.FkVocTipoSogc getFkVocTipoSogc() {
        return fkVocTipoSogc;
    }

    /**
     * Sets the value of the fkVocTipoSogc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSogc.FkVocTipoSogc }
     *     
     */
    public void setFkVocTipoSogc(DSogc.FkVocTipoSogc value) {
        this.fkVocTipoSogc = value;
    }

    /**
     * Gets the value of the flagAmmneAttivaTf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFlagAmmneAttivaTf() {
        return flagAmmneAttivaTf;
    }

    /**
     * Sets the value of the flagAmmneAttivaTf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFlagAmmneAttivaTf(Boolean value) {
        this.flagAmmneAttivaTf = value;
    }

    /**
     * Gets the value of the fkFonte property.
     * 
     * @return
     *     possible object is
     *     {@link DSogc.FkFonte }
     *     
     */
    public DSogc.FkFonte getFkFonte() {
        return fkFonte;
    }

    /**
     * Sets the value of the fkFonte property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSogc.FkFonte }
     *     
     */
    public void setFkFonte(DSogc.FkFonte value) {
        this.fkFonte = value;
    }

    /**
     * Gets the value of the codiIsil property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCodiIsil() {
        return codiIsil;
    }

    /**
     * Sets the value of the codiIsil property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodiIsil(JAXBElement<String> value) {
        this.codiIsil = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textNazioneIsad property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextNazioneIsad() {
        return textNazioneIsad;
    }

    /**
     * Sets the value of the textNazioneIsad property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextNazioneIsad(JAXBElement<String> value) {
        this.textNazioneIsad = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textCodiceIsad property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextCodiceIsad() {
        return textCodiceIsad;
    }

    /**
     * Sets the value of the textCodiceIsad property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextCodiceIsad(JAXBElement<String> value) {
        this.textCodiceIsad = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textSiglaIsad property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextSiglaIsad() {
        return textSiglaIsad;
    }

    /**
     * Sets the value of the textSiglaIsad property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextSiglaIsad(JAXBElement<String> value) {
        this.textSiglaIsad = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textAcronimo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextAcronimo() {
        return textAcronimo;
    }

    /**
     * Sets the value of the textAcronimo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextAcronimo(JAXBElement<String> value) {
        this.textAcronimo = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textDenUniformata property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextDenUniformata() {
        return textDenUniformata;
    }

    /**
     * Sets the value of the textDenUniformata property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextDenUniformata(JAXBElement<String> value) {
        this.textDenUniformata = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the fkVocNaturagiuridica property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocNaturagiuridica }{@code >}
     *     
     */
    public JAXBElement<DSogc.FkVocNaturagiuridica> getFkVocNaturagiuridica() {
        return fkVocNaturagiuridica;
    }

    /**
     * Sets the value of the fkVocNaturagiuridica property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocNaturagiuridica }{@code >}
     *     
     */
    public void setFkVocNaturagiuridica(JAXBElement<DSogc.FkVocNaturagiuridica> value) {
        this.fkVocNaturagiuridica = ((JAXBElement<DSogc.FkVocNaturagiuridica> ) value);
    }

    /**
     * Gets the value of the textEstrCronoTestuali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextEstrCronoTestuali() {
        return textEstrCronoTestuali;
    }

    /**
     * Sets the value of the textEstrCronoTestuali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextEstrCronoTestuali(String value) {
        this.textEstrCronoTestuali = value;
    }

    /**
     * Gets the value of the dateEstremoRemoto property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDateEstremoRemoto() {
        return dateEstremoRemoto;
    }

    /**
     * Sets the value of the dateEstremoRemoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDateEstremoRemoto(JAXBElement<XMLGregorianCalendar> value) {
        this.dateEstremoRemoto = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the textSecoloRm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextSecoloRm() {
        return textSecoloRm;
    }

    /**
     * Sets the value of the textSecoloRm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextSecoloRm(JAXBElement<String> value) {
        this.textSecoloRm = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the fkVocValiditaDtrm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocValiditaDtrm }{@code >}
     *     
     */
    public JAXBElement<DSogc.FkVocValiditaDtrm> getFkVocValiditaDtrm() {
        return fkVocValiditaDtrm;
    }

    /**
     * Sets the value of the fkVocValiditaDtrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocValiditaDtrm }{@code >}
     *     
     */
    public void setFkVocValiditaDtrm(JAXBElement<DSogc.FkVocValiditaDtrm> value) {
        this.fkVocValiditaDtrm = ((JAXBElement<DSogc.FkVocValiditaDtrm> ) value);
    }

    /**
     * Gets the value of the fkVocSpecificaSerm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocSpecificaSerm }{@code >}
     *     
     */
    public JAXBElement<DSogc.FkVocSpecificaSerm> getFkVocSpecificaSerm() {
        return fkVocSpecificaSerm;
    }

    /**
     * Sets the value of the fkVocSpecificaSerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocSpecificaSerm }{@code >}
     *     
     */
    public void setFkVocSpecificaSerm(JAXBElement<DSogc.FkVocSpecificaSerm> value) {
        this.fkVocSpecificaSerm = ((JAXBElement<DSogc.FkVocSpecificaSerm> ) value);
    }

    /**
     * Gets the value of the dateEstremoRecente property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getDateEstremoRecente() {
        return dateEstremoRecente;
    }

    /**
     * Sets the value of the dateEstremoRecente property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setDateEstremoRecente(JAXBElement<XMLGregorianCalendar> value) {
        this.dateEstremoRecente = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the textSecoloRe property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextSecoloRe() {
        return textSecoloRe;
    }

    /**
     * Sets the value of the textSecoloRe property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextSecoloRe(JAXBElement<String> value) {
        this.textSecoloRe = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the fkVocValiditaDtre property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocValiditaDtre }{@code >}
     *     
     */
    public JAXBElement<DSogc.FkVocValiditaDtre> getFkVocValiditaDtre() {
        return fkVocValiditaDtre;
    }

    /**
     * Sets the value of the fkVocValiditaDtre property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocValiditaDtre }{@code >}
     *     
     */
    public void setFkVocValiditaDtre(JAXBElement<DSogc.FkVocValiditaDtre> value) {
        this.fkVocValiditaDtre = ((JAXBElement<DSogc.FkVocValiditaDtre> ) value);
    }

    /**
     * Gets the value of the fkVocSpecificaSere property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocSpecificaSere }{@code >}
     *     
     */
    public JAXBElement<DSogc.FkVocSpecificaSere> getFkVocSpecificaSere() {
        return fkVocSpecificaSere;
    }

    /**
     * Sets the value of the fkVocSpecificaSere property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DSogc.FkVocSpecificaSere }{@code >}
     *     
     */
    public void setFkVocSpecificaSere(JAXBElement<DSogc.FkVocSpecificaSere> value) {
        this.fkVocSpecificaSere = ((JAXBElement<DSogc.FkVocSpecificaSere> ) value);
    }

    /**
     * Gets the value of the textNoteData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextNoteData() {
        return textNoteData;
    }

    /**
     * Sets the value of the textNoteData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextNoteData(JAXBElement<String> value) {
        this.textNoteData = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dSogcDenParallela property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dSogcDenParallela property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDSogcDenParallela().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DSogcDenParallela }
     * 
     * 
     */
    public List<DSogcDenParallela> getDSogcDenParallela() {
        if (dSogcDenParallela == null) {
            dSogcDenParallela = new ArrayList<DSogcDenParallela>();
        }
        return this.dSogcDenParallela;
    }

    /**
     * Gets the value of the dSogcAltreden property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dSogcAltreden property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDSogcAltreden().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DSogcAltreden }
     * 
     * 
     */
    public List<DSogcAltreden> getDSogcAltreden() {
        if (dSogcAltreden == null) {
            dSogcAltreden = new ArrayList<DSogcAltreden>();
        }
        return this.dSogcAltreden;
    }

    /**
     * Gets the value of the dSogcStatoLocali property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dSogcStatoLocali property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDSogcStatoLocali().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DSogcStatoLocali }
     * 
     * 
     */
    public List<DSogcStatoLocali> getDSogcStatoLocali() {
        if (dSogcStatoLocali == null) {
            dSogcStatoLocali = new ArrayList<DSogcStatoLocali>();
        }
        return this.dSogcStatoLocali;
    }

    /**
     * Gets the value of the dLocalizzazione property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dLocalizzazione property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDLocalizzazione().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DLocalizzazione }
     * 
     * 
     */
    public List<DLocalizzazione> getDLocalizzazione() {
        if (dLocalizzazione == null) {
            dLocalizzazione = new ArrayList<DLocalizzazione>();
        }
        return this.dLocalizzazione;
    }

    /**
     * Gets the value of the textCircEcclesiastica property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextCircEcclesiastica() {
        return textCircEcclesiastica;
    }

    /**
     * Sets the value of the textCircEcclesiastica property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextCircEcclesiastica(JAXBElement<String> value) {
        this.textCircEcclesiastica = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dContatti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dContatti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDContatti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DContatti }
     * 
     * 
     */
    public List<DContatti> getDContatti() {
        if (dContatti == null) {
            dContatti = new ArrayList<DContatti>();
        }
        return this.dContatti;
    }

    /**
     * Gets the value of the textCenniStoriciIsti property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextCenniStoriciIsti() {
        return textCenniStoriciIsti;
    }

    /**
     * Sets the value of the textCenniStoriciIsti property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextCenniStoriciIsti(JAXBElement<String> value) {
        this.textCenniStoriciIsti = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textContestoTerritorialeCult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextContestoTerritorialeCult() {
        return textContestoTerritorialeCult;
    }

    /**
     * Sets the value of the textContestoTerritorialeCult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextContestoTerritorialeCult(JAXBElement<String> value) {
        this.textContestoTerritorialeCult = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textMandatoFontiNormative property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextMandatoFontiNormative() {
        return textMandatoFontiNormative;
    }

    /**
     * Sets the value of the textMandatoFontiNormative property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextMandatoFontiNormative(JAXBElement<String> value) {
        this.textMandatoFontiNormative = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textStrutturaAmministrativa property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextStrutturaAmministrativa() {
        return textStrutturaAmministrativa;
    }

    /**
     * Sets the value of the textStrutturaAmministrativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextStrutturaAmministrativa(JAXBElement<String> value) {
        this.textStrutturaAmministrativa = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textPoliticheGestioneDoc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextPoliticheGestioneDoc() {
        return textPoliticheGestioneDoc;
    }

    /**
     * Sets the value of the textPoliticheGestioneDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextPoliticheGestioneDoc(JAXBElement<String> value) {
        this.textPoliticheGestioneDoc = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textEdifici property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextEdifici() {
        return textEdifici;
    }

    /**
     * Sets the value of the textEdifici property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextEdifici(JAXBElement<String> value) {
        this.textEdifici = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textPatrimonioArchivistico property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextPatrimonioArchivistico() {
        return textPatrimonioArchivistico;
    }

    /**
     * Sets the value of the textPatrimonioArchivistico property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextPatrimonioArchivistico(JAXBElement<String> value) {
        this.textPatrimonioArchivistico = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textStrumentiRicerca property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextStrumentiRicerca() {
        return textStrumentiRicerca;
    }

    /**
     * Sets the value of the textStrumentiRicerca property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextStrumentiRicerca(JAXBElement<String> value) {
        this.textStrumentiRicerca = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DUrl }
     * 
     * 
     */
    public List<DUrl> getDUrl() {
        if (dUrl == null) {
            dUrl = new ArrayList<DUrl>();
        }
        return this.dUrl;
    }

    /**
     * Gets the value of the codiSan property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCodiSan() {
        return codiSan;
    }

    /**
     * Sets the value of the codiSan property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCodiSan(JAXBElement<String> value) {
        this.codiSan = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textIstResp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextIstResp() {
        return textIstResp;
    }

    /**
     * Sets the value of the textIstResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextIstResp(JAXBElement<String> value) {
        this.textIstResp = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textNormeConvenzioni property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextNormeConvenzioni() {
        return textNormeConvenzioni;
    }

    /**
     * Sets the value of the textNormeConvenzioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextNormeConvenzioni(JAXBElement<String> value) {
        this.textNormeConvenzioni = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textGradoElaborazione property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextGradoElaborazione() {
        return textGradoElaborazione;
    }

    /**
     * Sets the value of the textGradoElaborazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextGradoElaborazione(JAXBElement<String> value) {
        this.textGradoElaborazione = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textLivelloCompletezza property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextLivelloCompletezza() {
        return textLivelloCompletezza;
    }

    /**
     * Sets the value of the textLivelloCompletezza property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextLivelloCompletezza(JAXBElement<String> value) {
        this.textLivelloCompletezza = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the textFontiInformative property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextFontiInformative() {
        return textFontiInformative;
    }

    /**
     * Sets the value of the textFontiInformative property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextFontiInformative(JAXBElement<String> value) {
        this.textFontiInformative = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the dCompilatore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dCompilatore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDCompilatore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DCompilatore }
     * 
     * 
     */
    public List<DCompilatore> getDCompilatore() {
        if (dCompilatore == null) {
            dCompilatore = new ArrayList<DCompilatore>();
        }
        return this.dCompilatore;
    }

    /**
     * Gets the value of the textLinguaScrittura property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextLinguaScrittura() {
        return textLinguaScrittura;
    }

    /**
     * Sets the value of the textLinguaScrittura property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextLinguaScrittura(JAXBElement<String> value) {
        this.textLinguaScrittura = ((JAXBElement<String> ) value);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/fonti}prof_group"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "profGroup"
    })
    public static class FkFonte {

        @XmlElement(name = "prof_group", namespace = "http://sas.beniculturali.it/catalogo/fonti")
        protected ProfGroup profGroup;

        /**
         * Gets the value of the profGroup property.
         * 
         * @return
         *     possible object is
         *     {@link ProfGroup }
         *     
         */
        public ProfGroup getProfGroup() {
            return profGroup;
        }

        /**
         * Sets the value of the profGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProfGroup }
         *     
         */
        public void setProfGroup(ProfGroup value) {
            this.profGroup = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogc}d_voc_naturagiuridica"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocNaturagiuridica"
    })
    public static class FkVocNaturagiuridica {

        @XmlElement(name = "d_voc_naturagiuridica", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-sogc")
        protected DVocNaturagiuridica dVocNaturagiuridica;

        /**
         * Gets the value of the dVocNaturagiuridica property.
         * 
         * @return
         *     possible object is
         *     {@link DVocNaturagiuridica }
         *     
         */
        public DVocNaturagiuridica getDVocNaturagiuridica() {
            return dVocNaturagiuridica;
        }

        /**
         * Sets the value of the dVocNaturagiuridica property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocNaturagiuridica }
         *     
         */
        public void setDVocNaturagiuridica(DVocNaturagiuridica value) {
            this.dVocNaturagiuridica = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_specifica_secoli"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocSpecificaSecoli"
    })
    public static class FkVocSpecificaSere {

        @XmlElement(name = "d_voc_specifica_secoli", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-trasv")
        protected DVocSpecificaSecoli dVocSpecificaSecoli;

        /**
         * Gets the value of the dVocSpecificaSecoli property.
         * 
         * @return
         *     possible object is
         *     {@link DVocSpecificaSecoli }
         *     
         */
        public DVocSpecificaSecoli getDVocSpecificaSecoli() {
            return dVocSpecificaSecoli;
        }

        /**
         * Sets the value of the dVocSpecificaSecoli property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocSpecificaSecoli }
         *     
         */
        public void setDVocSpecificaSecoli(DVocSpecificaSecoli value) {
            this.dVocSpecificaSecoli = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_specifica_secoli"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocSpecificaSecoli"
    })
    public static class FkVocSpecificaSerm {

        @XmlElement(name = "d_voc_specifica_secoli", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-trasv")
        protected DVocSpecificaSecoli dVocSpecificaSecoli;

        /**
         * Gets the value of the dVocSpecificaSecoli property.
         * 
         * @return
         *     possible object is
         *     {@link DVocSpecificaSecoli }
         *     
         */
        public DVocSpecificaSecoli getDVocSpecificaSecoli() {
            return dVocSpecificaSecoli;
        }

        /**
         * Sets the value of the dVocSpecificaSecoli property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocSpecificaSecoli }
         *     
         */
        public void setDVocSpecificaSecoli(DVocSpecificaSecoli value) {
            this.dVocSpecificaSecoli = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogc}d_voc_tipo_sogc"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocTipoSogc"
    })
    public static class FkVocTipoSogc {

        @XmlElement(name = "d_voc_tipo_sogc", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-sogc")
        protected DVocTipoSogc dVocTipoSogc;

        /**
         * Gets the value of the dVocTipoSogc property.
         * 
         * @return
         *     possible object is
         *     {@link DVocTipoSogc }
         *     
         */
        public DVocTipoSogc getDVocTipoSogc() {
            return dVocTipoSogc;
        }

        /**
         * Sets the value of the dVocTipoSogc property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocTipoSogc }
         *     
         */
        public void setDVocTipoSogc(DVocTipoSogc value) {
            this.dVocTipoSogc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_validita_date"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocValiditaDate"
    })
    public static class FkVocValiditaDtre {

        @XmlElement(name = "d_voc_validita_date", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-trasv")
        protected DVocValiditaDate dVocValiditaDate;

        /**
         * Gets the value of the dVocValiditaDate property.
         * 
         * @return
         *     possible object is
         *     {@link DVocValiditaDate }
         *     
         */
        public DVocValiditaDate getDVocValiditaDate() {
            return dVocValiditaDate;
        }

        /**
         * Sets the value of the dVocValiditaDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocValiditaDate }
         *     
         */
        public void setDVocValiditaDate(DVocValiditaDate value) {
            this.dVocValiditaDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-trasv}d_voc_validita_date"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocValiditaDate"
    })
    public static class FkVocValiditaDtrm {

        @XmlElement(name = "d_voc_validita_date", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-trasv")
        protected DVocValiditaDate dVocValiditaDate;

        /**
         * Gets the value of the dVocValiditaDate property.
         * 
         * @return
         *     possible object is
         *     {@link DVocValiditaDate }
         *     
         */
        public DVocValiditaDate getDVocValiditaDate() {
            return dVocValiditaDate;
        }

        /**
         * Sets the value of the dVocValiditaDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocValiditaDate }
         *     
         */
        public void setDVocValiditaDate(DVocValiditaDate value) {
            this.dVocValiditaDate = value;
        }

    }

}
