//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 10:27:57 AM CET 
//


package it.beniculturali.sas.catalogo.comparc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.beniculturali.sas.catalogo.vocabolari_comparc.DVocTipoRappr;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fk_voc_tipo_rappr">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-comparc}d_voc_tipo_rappr"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fkVocTipoRappr"
})
@XmlRootElement(name = "d_comparc_tipo_rappr")
public class DComparcTipoRappr {

    @XmlElement(name = "fk_voc_tipo_rappr", required = true)
    protected DComparcTipoRappr.FkVocTipoRappr fkVocTipoRappr;

    /**
     * Gets the value of the fkVocTipoRappr property.
     * 
     * @return
     *     possible object is
     *     {@link DComparcTipoRappr.FkVocTipoRappr }
     *     
     */
    public DComparcTipoRappr.FkVocTipoRappr getFkVocTipoRappr() {
        return fkVocTipoRappr;
    }

    /**
     * Sets the value of the fkVocTipoRappr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DComparcTipoRappr.FkVocTipoRappr }
     *     
     */
    public void setFkVocTipoRappr(DComparcTipoRappr.FkVocTipoRappr value) {
        this.fkVocTipoRappr = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-comparc}d_voc_tipo_rappr"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocTipoRappr"
    })
    public static class FkVocTipoRappr {

        @XmlElement(name = "d_voc_tipo_rappr", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-comparc")
        protected List<DVocTipoRappr> dVocTipoRappr;

        /**
         * Gets the value of the dVocTipoRappr property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dVocTipoRappr property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDVocTipoRappr().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DVocTipoRappr }
         * 
         * 
         */
        public List<DVocTipoRappr> getDVocTipoRappr() {
            if (dVocTipoRappr == null) {
                dVocTipoRappr = new ArrayList<DVocTipoRappr>();
            }
            return this.dVocTipoRappr;
        }

    }

}
