//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 04:50:28 PM CET 
//


package it.beniculturali.sas.catalogo.comparc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import it.beniculturali.sas.catalogo.commons.DCompilatore;
import it.beniculturali.sas.catalogo.commons.DUrl;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}codi_provenienza"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_comparc"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_den_uniformata"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_stato_descrizione"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}flag_comparc_proprieta_statale_tf"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_fonte"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_segn_definitiva" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_segn_provv" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_num_corda" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_num_corda_old" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_antiche_segnature" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_ua" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_sottotipo_ua" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_den_critica" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_lingua_den" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_data_topica" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_estr_crono_testuali"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}date_estremo_remoto" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_secolo_rm" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_validita_dtrm" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_specifica_serm" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}date_estremo_recente" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_secolo_re" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_validita_dtre" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_specifica_sere" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_note_data" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_altrecron" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_altreden" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_intestaz_autorita" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_qualita_scheda" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_dati_consistenza" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_supporto" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_tipo_supporto" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_stato_conservazione" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_formato" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_tipo_formato" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_legatura" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_legatura" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_legatura_prec" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_descr_estrinseca" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}nume_mt_lineari_complessivi" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}nume_riparto_mt_lineari_sottolvl" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_segni_convalida" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_danni" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_restauro" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_risorse_economiche" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_restauro" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_storia_ist_ammva" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_storia_archivistica" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_modalita_acq" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_categorie" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_area_tematica" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_voci_indice" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_rel_comparc_toponimi" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_antroponimi" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_famiglia" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_ente" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_contenuto" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_lingua_contenuto" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_tipo_scrittura_contenuto" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}flag_ordinamento_tf" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_stato_ordinamento" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_criteri_ordinamento" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}fk_voc_stato_inventariazione" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_cond_accesso" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}d_comparc_doccoll" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/comparc}text_note" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/commons}d_url" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://sas.beniculturali.it/catalogo/commons}d_compilatore" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codiProvenienza",
    "fkVocTipoComparc",
    "textDenUniformata",
    "fkVocStatoDescrizione",
    "flagComparcProprietaStataleTf",
    "fkFonte",
    "textSegnDefinitiva",
    "textSegnProvv",
    "textNumCorda",
    "textNumCordaOld",
    "dAnticheSegnature",
    "fkVocTipoUa",
    "fkVocSottotipoUa",
    "textDenCritica",
    "fkVocTipoLinguaDen",
    "textDataTopica",
    "textEstrCronoTestuali",
    "dateEstremoRemoto",
    "textSecoloRm",
    "fkVocValiditaDtrm",
    "fkVocSpecificaSerm",
    "dateEstremoRecente",
    "textSecoloRe",
    "fkVocValiditaDtre",
    "fkVocSpecificaSere",
    "textNoteData",
    "dComparcAltrecron",
    "dComparcAltreden",
    "dComparcIntestazAutorita",
    "fkVocQualitaScheda",
    "dComparcDatiConsistenza",
    "fkVocTipoSupporto",
    "textTipoSupporto",
    "fkVocStatoConservazione",
    "fkVocTipoFormato",
    "textTipoFormato",
    "fkVocTipoLegatura",
    "textLegatura",
    "textLegaturaPrec",
    "textDescrEstrinseca",
    "numeMtLineariComplessivi",
    "numeRipartoMtLineariSottolvl",
    "textSegniConvalida",
    "dComparcDanni",
    "textRestauro",
    "textRisorseEconomiche",
    "dComparcRestauro",
    "textStoriaIstAmmva",
    "textStoriaArchivistica",
    "fkVocModalitaAcq",
    "dComparcCategorie",
    "dComparcAreaTematica",
    "dComparcVociIndice",
    "dRelComparcToponimi",
    "dComparcAntroponimi",
    "dComparcFamiglia",
    "dComparcEnte",
    "textContenuto",
    "fkVocTipoLinguaContenuto",
    "fkVocTipoScritturaContenuto",
    "flagOrdinamentoTf",
    "fkVocStatoOrdinamento",
    "textCriteriOrdinamento",
    "fkVocStatoInventariazione",
    "dComparcCondAccesso",
    "dComparcDoccoll",
    "textNote",
    "dUrl",
    "dCompilatore"
})
@XmlRootElement(name = "d_comparc_ua")
public class DComparcUa {

    @XmlElement(name = "codi_provenienza", required = true)
    protected String codiProvenienza;
    @XmlElement(name = "fk_voc_tipo_comparc", required = true)
    protected FkVocTipoComparc fkVocTipoComparc;
    @XmlElement(name = "text_den_uniformata", required = true)
    protected String textDenUniformata;
    @XmlElement(name = "fk_voc_stato_descrizione", required = true, nillable = true)
    protected FkVocStatoDescrizione fkVocStatoDescrizione;
    @XmlElement(name = "flag_comparc_proprieta_statale_tf", required = true, nillable = true)
    protected String flagComparcProprietaStataleTf;
    @XmlElement(name = "fk_fonte", required = true)
    protected FkFonte fkFonte;
    @XmlElement(name = "text_segn_definitiva", nillable = true)
    protected String textSegnDefinitiva;
    @XmlElement(name = "text_segn_provv", nillable = true)
    protected String textSegnProvv;
    @XmlElement(name = "text_num_corda", nillable = true)
    protected Integer textNumCorda;
    @XmlElement(name = "text_num_corda_old", nillable = true)
    protected Integer textNumCordaOld;
    @XmlElement(name = "d_antiche_segnature")
    protected List<DAnticheSegnature> dAnticheSegnature;
    @XmlElement(name = "fk_voc_tipo_ua", nillable = true)
    protected FkVocTipoUa fkVocTipoUa;
    @XmlElement(name = "fk_voc_sottotipo_ua", nillable = true)
    protected FkVocSottotipoUa fkVocSottotipoUa;
    @XmlElement(name = "text_den_critica", nillable = true)
    protected String textDenCritica;
    @XmlElement(name = "fk_voc_tipo_lingua_den", nillable = true)
    protected FkVocTipoLinguaDen fkVocTipoLinguaDen;
    @XmlElement(name = "text_data_topica", nillable = true)
    protected String textDataTopica;
    @XmlElement(name = "text_estr_crono_testuali", required = true)
    protected String textEstrCronoTestuali;
    @XmlElement(name = "date_estremo_remoto", nillable = true)
    protected XMLGregorianCalendar dateEstremoRemoto;
    @XmlElement(name = "text_secolo_rm", nillable = true)
    protected String textSecoloRm;
    @XmlElement(name = "fk_voc_validita_dtrm", nillable = true)
    protected FkVocValiditaDtrm fkVocValiditaDtrm;
    @XmlElement(name = "fk_voc_specifica_serm", nillable = true)
    protected FkVocSpecificaSerm fkVocSpecificaSerm;
    @XmlElement(name = "date_estremo_recente", nillable = true)
    protected XMLGregorianCalendar dateEstremoRecente;
    @XmlElement(name = "text_secolo_re", nillable = true)
    protected String textSecoloRe;
    @XmlElement(name = "fk_voc_validita_dtre", nillable = true)
    protected FkVocValiditaDtre fkVocValiditaDtre;
    @XmlElement(name = "fk_voc_specifica_sere", nillable = true)
    protected FkVocSpecificaSere fkVocSpecificaSere;
    @XmlElement(name = "text_note_data", nillable = true)
    protected String textNoteData;
    @XmlElement(name = "d_comparc_altrecron")
    protected List<DComparcAltrecron> dComparcAltrecron;
    @XmlElement(name = "d_comparc_altreden")
    protected List<DComparcAltreden> dComparcAltreden;
    @XmlElement(name = "d_comparc_intestaz_autorita")
    protected List<DComparcIntestazAutorita> dComparcIntestazAutorita;
    @XmlElement(name = "fk_voc_qualita_scheda", nillable = true)
    protected FkVocQualitaScheda fkVocQualitaScheda;
    @XmlElement(name = "d_comparc_dati_consistenza")
    protected List<DComparcDatiConsistenza> dComparcDatiConsistenza;
    @XmlElement(name = "fk_voc_tipo_supporto", nillable = true)
    protected FkVocTipoSupporto fkVocTipoSupporto;
    @XmlElement(name = "text_tipo_supporto", nillable = true)
    protected String textTipoSupporto;
    @XmlElement(name = "fk_voc_stato_conservazione", nillable = true)
    protected FkVocStatoConservazione fkVocStatoConservazione;
    @XmlElement(name = "fk_voc_tipo_formato", nillable = true)
    protected FkVocTipoFormato fkVocTipoFormato;
    @XmlElement(name = "text_tipo_formato", nillable = true)
    protected String textTipoFormato;
    @XmlElement(name = "fk_voc_tipo_legatura", nillable = true)
    protected FkVocTipoLegatura fkVocTipoLegatura;
    @XmlElement(name = "text_legatura", nillable = true)
    protected String textLegatura;
    @XmlElement(name = "text_legatura_prec", nillable = true)
    protected String textLegaturaPrec;
    @XmlElement(name = "text_descr_estrinseca", nillable = true)
    protected String textDescrEstrinseca;
    @XmlElement(name = "nume_mt_lineari_complessivi", defaultValue = "0", nillable = true)
    protected BigDecimal numeMtLineariComplessivi;
    @XmlElement(name = "nume_riparto_mt_lineari_sottolvl", defaultValue = "0", nillable = true)
    protected BigDecimal numeRipartoMtLineariSottolvl;
    @XmlElement(name = "text_segni_convalida", nillable = true)
    protected String textSegniConvalida;
    @XmlElement(name = "d_comparc_danni")
    protected List<DComparcDanni> dComparcDanni;
    @XmlElement(name = "text_restauro", nillable = true)
    protected String textRestauro;
    @XmlElement(name = "text_risorse_economiche", nillable = true)
    protected String textRisorseEconomiche;
    @XmlElement(name = "d_comparc_restauro")
    protected List<DComparcRestauro> dComparcRestauro;
    @XmlElement(name = "text_storia_ist_ammva", nillable = true)
    protected String textStoriaIstAmmva;
    @XmlElement(name = "text_storia_archivistica", nillable = true)
    protected String textStoriaArchivistica;
    @XmlElement(name = "fk_voc_modalita_acq", nillable = true)
    protected FkVocModalitaAcq fkVocModalitaAcq;
    @XmlElement(name = "d_comparc_categorie")
    protected List<DComparcCategorie> dComparcCategorie;
    @XmlElement(name = "d_comparc_area_tematica")
    protected List<DComparcAreaTematica> dComparcAreaTematica;
    @XmlElement(name = "d_comparc_voci_indice")
    protected List<DComparcVociIndice> dComparcVociIndice;
    @XmlElement(name = "d_rel_comparc_toponimi")
    protected List<DRelComparcToponimi> dRelComparcToponimi;
    @XmlElement(name = "d_comparc_antroponimi")
    protected List<DComparcAntroponimi> dComparcAntroponimi;
    @XmlElement(name = "d_comparc_famiglia")
    protected List<DComparcFamiglia> dComparcFamiglia;
    @XmlElement(name = "d_comparc_ente")
    protected List<DComparcEnte> dComparcEnte;
    @XmlElement(name = "text_contenuto", nillable = true)
    protected String textContenuto;
    @XmlElement(name = "fk_voc_tipo_lingua_contenuto", nillable = true)
    protected FkVocTipoLinguaContenuto fkVocTipoLinguaContenuto;
    @XmlElement(name = "fk_voc_tipo_scrittura_contenuto", nillable = true)
    protected FkVocTipoScritturaContenuto fkVocTipoScritturaContenuto;
    @XmlElement(name = "flag_ordinamento_tf", nillable = true)
    protected Boolean flagOrdinamentoTf;
    @XmlElement(name = "fk_voc_stato_ordinamento", nillable = true)
    protected FkVocStatoOrdinamento fkVocStatoOrdinamento;
    @XmlElement(name = "text_criteri_ordinamento", nillable = true)
    protected String textCriteriOrdinamento;
    @XmlElement(name = "fk_voc_stato_inventariazione", nillable = true)
    protected FkVocStatoInventariazione fkVocStatoInventariazione;
    @XmlElement(name = "d_comparc_cond_accesso")
    protected List<DComparcCondAccesso> dComparcCondAccesso;
    @XmlElement(name = "d_comparc_doccoll")
    protected List<DComparcDoccoll> dComparcDoccoll;
    @XmlElement(name = "text_note", nillable = true)
    protected String textNote;
    @XmlElement(name = "d_url", namespace = "http://sas.beniculturali.it/catalogo/commons")
    protected List<DUrl> dUrl;
    @XmlElement(name = "d_compilatore", namespace = "http://sas.beniculturali.it/catalogo/commons")
    protected List<DCompilatore> dCompilatore;

    /**
     * Gets the value of the codiProvenienza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiProvenienza() {
        return codiProvenienza;
    }

    /**
     * Sets the value of the codiProvenienza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiProvenienza(String value) {
        this.codiProvenienza = value;
    }

    /**
     * Gets the value of the fkVocTipoComparc property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoComparc }
     *     
     */
    public FkVocTipoComparc getFkVocTipoComparc() {
        return fkVocTipoComparc;
    }

    /**
     * Sets the value of the fkVocTipoComparc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoComparc }
     *     
     */
    public void setFkVocTipoComparc(FkVocTipoComparc value) {
        this.fkVocTipoComparc = value;
    }

    /**
     * Gets the value of the textDenUniformata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDenUniformata() {
        return textDenUniformata;
    }

    /**
     * Sets the value of the textDenUniformata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDenUniformata(String value) {
        this.textDenUniformata = value;
    }

    /**
     * Gets the value of the fkVocStatoDescrizione property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocStatoDescrizione }
     *     
     */
    public FkVocStatoDescrizione getFkVocStatoDescrizione() {
        return fkVocStatoDescrizione;
    }

    /**
     * Sets the value of the fkVocStatoDescrizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocStatoDescrizione }
     *     
     */
    public void setFkVocStatoDescrizione(FkVocStatoDescrizione value) {
        this.fkVocStatoDescrizione = value;
    }

    /**
     * Gets the value of the flagComparcProprietaStataleTf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagComparcProprietaStataleTf() {
        return flagComparcProprietaStataleTf;
    }

    /**
     * Sets the value of the flagComparcProprietaStataleTf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagComparcProprietaStataleTf(String value) {
        this.flagComparcProprietaStataleTf = value;
    }

    /**
     * Gets the value of the fkFonte property.
     * 
     * @return
     *     possible object is
     *     {@link FkFonte }
     *     
     */
    public FkFonte getFkFonte() {
        return fkFonte;
    }

    /**
     * Sets the value of the fkFonte property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkFonte }
     *     
     */
    public void setFkFonte(FkFonte value) {
        this.fkFonte = value;
    }

    /**
     * Gets the value of the textSegnDefinitiva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSegnDefinitiva() {
        return textSegnDefinitiva;
    }

    /**
     * Sets the value of the textSegnDefinitiva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSegnDefinitiva(String value) {
        this.textSegnDefinitiva = value;
    }

    /**
     * Gets the value of the textSegnProvv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSegnProvv() {
        return textSegnProvv;
    }

    /**
     * Sets the value of the textSegnProvv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSegnProvv(String value) {
        this.textSegnProvv = value;
    }

    /**
     * Gets the value of the textNumCorda property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTextNumCorda() {
        return textNumCorda;
    }

    /**
     * Sets the value of the textNumCorda property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextNumCorda(Integer value) {
        this.textNumCorda = value;
    }

    /**
     * Gets the value of the textNumCordaOld property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTextNumCordaOld() {
        return textNumCordaOld;
    }

    /**
     * Sets the value of the textNumCordaOld property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTextNumCordaOld(Integer value) {
        this.textNumCordaOld = value;
    }

    /**
     * Gets the value of the dAnticheSegnature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dAnticheSegnature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDAnticheSegnature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DAnticheSegnature }
     * 
     * 
     */
    public List<DAnticheSegnature> getDAnticheSegnature() {
        if (dAnticheSegnature == null) {
            dAnticheSegnature = new ArrayList<DAnticheSegnature>();
        }
        return this.dAnticheSegnature;
    }

    /**
     * Gets the value of the fkVocTipoUa property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoUa }
     *     
     */
    public FkVocTipoUa getFkVocTipoUa() {
        return fkVocTipoUa;
    }

    /**
     * Sets the value of the fkVocTipoUa property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoUa }
     *     
     */
    public void setFkVocTipoUa(FkVocTipoUa value) {
        this.fkVocTipoUa = value;
    }

    /**
     * Gets the value of the fkVocSottotipoUa property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocSottotipoUa }
     *     
     */
    public FkVocSottotipoUa getFkVocSottotipoUa() {
        return fkVocSottotipoUa;
    }

    /**
     * Sets the value of the fkVocSottotipoUa property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocSottotipoUa }
     *     
     */
    public void setFkVocSottotipoUa(FkVocSottotipoUa value) {
        this.fkVocSottotipoUa = value;
    }

    /**
     * Gets the value of the textDenCritica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDenCritica() {
        return textDenCritica;
    }

    /**
     * Sets the value of the textDenCritica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDenCritica(String value) {
        this.textDenCritica = value;
    }

    /**
     * Gets the value of the fkVocTipoLinguaDen property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoLinguaDen }
     *     
     */
    public FkVocTipoLinguaDen getFkVocTipoLinguaDen() {
        return fkVocTipoLinguaDen;
    }

    /**
     * Sets the value of the fkVocTipoLinguaDen property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoLinguaDen }
     *     
     */
    public void setFkVocTipoLinguaDen(FkVocTipoLinguaDen value) {
        this.fkVocTipoLinguaDen = value;
    }

    /**
     * Gets the value of the textDataTopica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDataTopica() {
        return textDataTopica;
    }

    /**
     * Sets the value of the textDataTopica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDataTopica(String value) {
        this.textDataTopica = value;
    }

    /**
     * Gets the value of the textEstrCronoTestuali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextEstrCronoTestuali() {
        return textEstrCronoTestuali;
    }

    /**
     * Sets the value of the textEstrCronoTestuali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextEstrCronoTestuali(String value) {
        this.textEstrCronoTestuali = value;
    }

    /**
     * Gets the value of the dateEstremoRemoto property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEstremoRemoto() {
        return dateEstremoRemoto;
    }

    /**
     * Sets the value of the dateEstremoRemoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEstremoRemoto(XMLGregorianCalendar value) {
        this.dateEstremoRemoto = value;
    }

    /**
     * Gets the value of the textSecoloRm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSecoloRm() {
        return textSecoloRm;
    }

    /**
     * Sets the value of the textSecoloRm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSecoloRm(String value) {
        this.textSecoloRm = value;
    }

    /**
     * Gets the value of the fkVocValiditaDtrm property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocValiditaDtrm }
     *     
     */
    public FkVocValiditaDtrm getFkVocValiditaDtrm() {
        return fkVocValiditaDtrm;
    }

    /**
     * Sets the value of the fkVocValiditaDtrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocValiditaDtrm }
     *     
     */
    public void setFkVocValiditaDtrm(FkVocValiditaDtrm value) {
        this.fkVocValiditaDtrm = value;
    }

    /**
     * Gets the value of the fkVocSpecificaSerm property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocSpecificaSerm }
     *     
     */
    public FkVocSpecificaSerm getFkVocSpecificaSerm() {
        return fkVocSpecificaSerm;
    }

    /**
     * Sets the value of the fkVocSpecificaSerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocSpecificaSerm }
     *     
     */
    public void setFkVocSpecificaSerm(FkVocSpecificaSerm value) {
        this.fkVocSpecificaSerm = value;
    }

    /**
     * Gets the value of the dateEstremoRecente property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEstremoRecente() {
        return dateEstremoRecente;
    }

    /**
     * Sets the value of the dateEstremoRecente property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEstremoRecente(XMLGregorianCalendar value) {
        this.dateEstremoRecente = value;
    }

    /**
     * Gets the value of the textSecoloRe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSecoloRe() {
        return textSecoloRe;
    }

    /**
     * Sets the value of the textSecoloRe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSecoloRe(String value) {
        this.textSecoloRe = value;
    }

    /**
     * Gets the value of the fkVocValiditaDtre property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocValiditaDtre }
     *     
     */
    public FkVocValiditaDtre getFkVocValiditaDtre() {
        return fkVocValiditaDtre;
    }

    /**
     * Sets the value of the fkVocValiditaDtre property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocValiditaDtre }
     *     
     */
    public void setFkVocValiditaDtre(FkVocValiditaDtre value) {
        this.fkVocValiditaDtre = value;
    }

    /**
     * Gets the value of the fkVocSpecificaSere property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocSpecificaSere }
     *     
     */
    public FkVocSpecificaSere getFkVocSpecificaSere() {
        return fkVocSpecificaSere;
    }

    /**
     * Sets the value of the fkVocSpecificaSere property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocSpecificaSere }
     *     
     */
    public void setFkVocSpecificaSere(FkVocSpecificaSere value) {
        this.fkVocSpecificaSere = value;
    }

    /**
     * Gets the value of the textNoteData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextNoteData() {
        return textNoteData;
    }

    /**
     * Sets the value of the textNoteData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextNoteData(String value) {
        this.textNoteData = value;
    }

    /**
     * Gets the value of the dComparcAltrecron property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcAltrecron property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcAltrecron().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcAltrecron }
     * 
     * 
     */
    public List<DComparcAltrecron> getDComparcAltrecron() {
        if (dComparcAltrecron == null) {
            dComparcAltrecron = new ArrayList<DComparcAltrecron>();
        }
        return this.dComparcAltrecron;
    }

    /**
     * Gets the value of the dComparcAltreden property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcAltreden property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcAltreden().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcAltreden }
     * 
     * 
     */
    public List<DComparcAltreden> getDComparcAltreden() {
        if (dComparcAltreden == null) {
            dComparcAltreden = new ArrayList<DComparcAltreden>();
        }
        return this.dComparcAltreden;
    }

    /**
     * Gets the value of the dComparcIntestazAutorita property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcIntestazAutorita property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcIntestazAutorita().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcIntestazAutorita }
     * 
     * 
     */
    public List<DComparcIntestazAutorita> getDComparcIntestazAutorita() {
        if (dComparcIntestazAutorita == null) {
            dComparcIntestazAutorita = new ArrayList<DComparcIntestazAutorita>();
        }
        return this.dComparcIntestazAutorita;
    }

    /**
     * Gets the value of the fkVocQualitaScheda property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocQualitaScheda }
     *     
     */
    public FkVocQualitaScheda getFkVocQualitaScheda() {
        return fkVocQualitaScheda;
    }

    /**
     * Sets the value of the fkVocQualitaScheda property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocQualitaScheda }
     *     
     */
    public void setFkVocQualitaScheda(FkVocQualitaScheda value) {
        this.fkVocQualitaScheda = value;
    }

    /**
     * Gets the value of the dComparcDatiConsistenza property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcDatiConsistenza property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcDatiConsistenza().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcDatiConsistenza }
     * 
     * 
     */
    public List<DComparcDatiConsistenza> getDComparcDatiConsistenza() {
        if (dComparcDatiConsistenza == null) {
            dComparcDatiConsistenza = new ArrayList<DComparcDatiConsistenza>();
        }
        return this.dComparcDatiConsistenza;
    }

    /**
     * Gets the value of the fkVocTipoSupporto property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoSupporto }
     *     
     */
    public FkVocTipoSupporto getFkVocTipoSupporto() {
        return fkVocTipoSupporto;
    }

    /**
     * Sets the value of the fkVocTipoSupporto property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoSupporto }
     *     
     */
    public void setFkVocTipoSupporto(FkVocTipoSupporto value) {
        this.fkVocTipoSupporto = value;
    }

    /**
     * Gets the value of the textTipoSupporto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextTipoSupporto() {
        return textTipoSupporto;
    }

    /**
     * Sets the value of the textTipoSupporto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextTipoSupporto(String value) {
        this.textTipoSupporto = value;
    }

    /**
     * Gets the value of the fkVocStatoConservazione property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocStatoConservazione }
     *     
     */
    public FkVocStatoConservazione getFkVocStatoConservazione() {
        return fkVocStatoConservazione;
    }

    /**
     * Sets the value of the fkVocStatoConservazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocStatoConservazione }
     *     
     */
    public void setFkVocStatoConservazione(FkVocStatoConservazione value) {
        this.fkVocStatoConservazione = value;
    }

    /**
     * Gets the value of the fkVocTipoFormato property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoFormato }
     *     
     */
    public FkVocTipoFormato getFkVocTipoFormato() {
        return fkVocTipoFormato;
    }

    /**
     * Sets the value of the fkVocTipoFormato property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoFormato }
     *     
     */
    public void setFkVocTipoFormato(FkVocTipoFormato value) {
        this.fkVocTipoFormato = value;
    }

    /**
     * Gets the value of the textTipoFormato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextTipoFormato() {
        return textTipoFormato;
    }

    /**
     * Sets the value of the textTipoFormato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextTipoFormato(String value) {
        this.textTipoFormato = value;
    }

    /**
     * Gets the value of the fkVocTipoLegatura property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoLegatura }
     *     
     */
    public FkVocTipoLegatura getFkVocTipoLegatura() {
        return fkVocTipoLegatura;
    }

    /**
     * Sets the value of the fkVocTipoLegatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoLegatura }
     *     
     */
    public void setFkVocTipoLegatura(FkVocTipoLegatura value) {
        this.fkVocTipoLegatura = value;
    }

    /**
     * Gets the value of the textLegatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLegatura() {
        return textLegatura;
    }

    /**
     * Sets the value of the textLegatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLegatura(String value) {
        this.textLegatura = value;
    }

    /**
     * Gets the value of the textLegaturaPrec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLegaturaPrec() {
        return textLegaturaPrec;
    }

    /**
     * Sets the value of the textLegaturaPrec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLegaturaPrec(String value) {
        this.textLegaturaPrec = value;
    }

    /**
     * Gets the value of the textDescrEstrinseca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDescrEstrinseca() {
        return textDescrEstrinseca;
    }

    /**
     * Sets the value of the textDescrEstrinseca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDescrEstrinseca(String value) {
        this.textDescrEstrinseca = value;
    }

    /**
     * Gets the value of the numeMtLineariComplessivi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumeMtLineariComplessivi() {
        return numeMtLineariComplessivi;
    }

    /**
     * Sets the value of the numeMtLineariComplessivi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumeMtLineariComplessivi(BigDecimal value) {
        this.numeMtLineariComplessivi = value;
    }

    /**
     * Gets the value of the numeRipartoMtLineariSottolvl property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumeRipartoMtLineariSottolvl() {
        return numeRipartoMtLineariSottolvl;
    }

    /**
     * Sets the value of the numeRipartoMtLineariSottolvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumeRipartoMtLineariSottolvl(BigDecimal value) {
        this.numeRipartoMtLineariSottolvl = value;
    }

    /**
     * Gets the value of the textSegniConvalida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSegniConvalida() {
        return textSegniConvalida;
    }

    /**
     * Sets the value of the textSegniConvalida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSegniConvalida(String value) {
        this.textSegniConvalida = value;
    }

    /**
     * Gets the value of the dComparcDanni property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcDanni property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcDanni().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcDanni }
     * 
     * 
     */
    public List<DComparcDanni> getDComparcDanni() {
        if (dComparcDanni == null) {
            dComparcDanni = new ArrayList<DComparcDanni>();
        }
        return this.dComparcDanni;
    }

    /**
     * Gets the value of the textRestauro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextRestauro() {
        return textRestauro;
    }

    /**
     * Sets the value of the textRestauro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextRestauro(String value) {
        this.textRestauro = value;
    }

    /**
     * Gets the value of the textRisorseEconomiche property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextRisorseEconomiche() {
        return textRisorseEconomiche;
    }

    /**
     * Sets the value of the textRisorseEconomiche property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextRisorseEconomiche(String value) {
        this.textRisorseEconomiche = value;
    }

    /**
     * Gets the value of the dComparcRestauro property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcRestauro property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcRestauro().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcRestauro }
     * 
     * 
     */
    public List<DComparcRestauro> getDComparcRestauro() {
        if (dComparcRestauro == null) {
            dComparcRestauro = new ArrayList<DComparcRestauro>();
        }
        return this.dComparcRestauro;
    }

    /**
     * Gets the value of the textStoriaIstAmmva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextStoriaIstAmmva() {
        return textStoriaIstAmmva;
    }

    /**
     * Sets the value of the textStoriaIstAmmva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextStoriaIstAmmva(String value) {
        this.textStoriaIstAmmva = value;
    }

    /**
     * Gets the value of the textStoriaArchivistica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextStoriaArchivistica() {
        return textStoriaArchivistica;
    }

    /**
     * Sets the value of the textStoriaArchivistica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextStoriaArchivistica(String value) {
        this.textStoriaArchivistica = value;
    }

    /**
     * Gets the value of the fkVocModalitaAcq property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocModalitaAcq }
     *     
     */
    public FkVocModalitaAcq getFkVocModalitaAcq() {
        return fkVocModalitaAcq;
    }

    /**
     * Sets the value of the fkVocModalitaAcq property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocModalitaAcq }
     *     
     */
    public void setFkVocModalitaAcq(FkVocModalitaAcq value) {
        this.fkVocModalitaAcq = value;
    }

    /**
     * Gets the value of the dComparcCategorie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcCategorie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcCategorie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcCategorie }
     * 
     * 
     */
    public List<DComparcCategorie> getDComparcCategorie() {
        if (dComparcCategorie == null) {
            dComparcCategorie = new ArrayList<DComparcCategorie>();
        }
        return this.dComparcCategorie;
    }

    /**
     * Gets the value of the dComparcAreaTematica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcAreaTematica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcAreaTematica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcAreaTematica }
     * 
     * 
     */
    public List<DComparcAreaTematica> getDComparcAreaTematica() {
        if (dComparcAreaTematica == null) {
            dComparcAreaTematica = new ArrayList<DComparcAreaTematica>();
        }
        return this.dComparcAreaTematica;
    }

    /**
     * Gets the value of the dComparcVociIndice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcVociIndice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcVociIndice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcVociIndice }
     * 
     * 
     */
    public List<DComparcVociIndice> getDComparcVociIndice() {
        if (dComparcVociIndice == null) {
            dComparcVociIndice = new ArrayList<DComparcVociIndice>();
        }
        return this.dComparcVociIndice;
    }

    /**
     * Gets the value of the dRelComparcToponimi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dRelComparcToponimi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDRelComparcToponimi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DRelComparcToponimi }
     * 
     * 
     */
    public List<DRelComparcToponimi> getDRelComparcToponimi() {
        if (dRelComparcToponimi == null) {
            dRelComparcToponimi = new ArrayList<DRelComparcToponimi>();
        }
        return this.dRelComparcToponimi;
    }

    /**
     * Gets the value of the dComparcAntroponimi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcAntroponimi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcAntroponimi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcAntroponimi }
     * 
     * 
     */
    public List<DComparcAntroponimi> getDComparcAntroponimi() {
        if (dComparcAntroponimi == null) {
            dComparcAntroponimi = new ArrayList<DComparcAntroponimi>();
        }
        return this.dComparcAntroponimi;
    }

    /**
     * Gets the value of the dComparcFamiglia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcFamiglia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcFamiglia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcFamiglia }
     * 
     * 
     */
    public List<DComparcFamiglia> getDComparcFamiglia() {
        if (dComparcFamiglia == null) {
            dComparcFamiglia = new ArrayList<DComparcFamiglia>();
        }
        return this.dComparcFamiglia;
    }

    /**
     * Gets the value of the dComparcEnte property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcEnte property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcEnte().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcEnte }
     * 
     * 
     */
    public List<DComparcEnte> getDComparcEnte() {
        if (dComparcEnte == null) {
            dComparcEnte = new ArrayList<DComparcEnte>();
        }
        return this.dComparcEnte;
    }

    /**
     * Gets the value of the textContenuto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextContenuto() {
        return textContenuto;
    }

    /**
     * Sets the value of the textContenuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextContenuto(String value) {
        this.textContenuto = value;
    }

    /**
     * Gets the value of the fkVocTipoLinguaContenuto property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoLinguaContenuto }
     *     
     */
    public FkVocTipoLinguaContenuto getFkVocTipoLinguaContenuto() {
        return fkVocTipoLinguaContenuto;
    }

    /**
     * Sets the value of the fkVocTipoLinguaContenuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoLinguaContenuto }
     *     
     */
    public void setFkVocTipoLinguaContenuto(FkVocTipoLinguaContenuto value) {
        this.fkVocTipoLinguaContenuto = value;
    }

    /**
     * Gets the value of the fkVocTipoScritturaContenuto property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocTipoScritturaContenuto }
     *     
     */
    public FkVocTipoScritturaContenuto getFkVocTipoScritturaContenuto() {
        return fkVocTipoScritturaContenuto;
    }

    /**
     * Sets the value of the fkVocTipoScritturaContenuto property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocTipoScritturaContenuto }
     *     
     */
    public void setFkVocTipoScritturaContenuto(FkVocTipoScritturaContenuto value) {
        this.fkVocTipoScritturaContenuto = value;
    }

    /**
     * Gets the value of the flagOrdinamentoTf property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFlagOrdinamentoTf() {
        return flagOrdinamentoTf;
    }

    /**
     * Sets the value of the flagOrdinamentoTf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFlagOrdinamentoTf(Boolean value) {
        this.flagOrdinamentoTf = value;
    }

    /**
     * Gets the value of the fkVocStatoOrdinamento property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocStatoOrdinamento }
     *     
     */
    public FkVocStatoOrdinamento getFkVocStatoOrdinamento() {
        return fkVocStatoOrdinamento;
    }

    /**
     * Sets the value of the fkVocStatoOrdinamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocStatoOrdinamento }
     *     
     */
    public void setFkVocStatoOrdinamento(FkVocStatoOrdinamento value) {
        this.fkVocStatoOrdinamento = value;
    }

    /**
     * Gets the value of the textCriteriOrdinamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextCriteriOrdinamento() {
        return textCriteriOrdinamento;
    }

    /**
     * Sets the value of the textCriteriOrdinamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextCriteriOrdinamento(String value) {
        this.textCriteriOrdinamento = value;
    }

    /**
     * Gets the value of the fkVocStatoInventariazione property.
     * 
     * @return
     *     possible object is
     *     {@link FkVocStatoInventariazione }
     *     
     */
    public FkVocStatoInventariazione getFkVocStatoInventariazione() {
        return fkVocStatoInventariazione;
    }

    /**
     * Sets the value of the fkVocStatoInventariazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link FkVocStatoInventariazione }
     *     
     */
    public void setFkVocStatoInventariazione(FkVocStatoInventariazione value) {
        this.fkVocStatoInventariazione = value;
    }

    /**
     * Gets the value of the dComparcCondAccesso property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcCondAccesso property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcCondAccesso().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcCondAccesso }
     * 
     * 
     */
    public List<DComparcCondAccesso> getDComparcCondAccesso() {
        if (dComparcCondAccesso == null) {
            dComparcCondAccesso = new ArrayList<DComparcCondAccesso>();
        }
        return this.dComparcCondAccesso;
    }

    /**
     * Gets the value of the dComparcDoccoll property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dComparcDoccoll property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDComparcDoccoll().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DComparcDoccoll }
     * 
     * 
     */
    public List<DComparcDoccoll> getDComparcDoccoll() {
        if (dComparcDoccoll == null) {
            dComparcDoccoll = new ArrayList<DComparcDoccoll>();
        }
        return this.dComparcDoccoll;
    }

    /**
     * Gets the value of the textNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextNote() {
        return textNote;
    }

    /**
     * Sets the value of the textNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextNote(String value) {
        this.textNote = value;
    }

    /**
     * Gets the value of the dUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DUrl }
     * 
     * 
     */
    public List<DUrl> getDUrl() {
        if (dUrl == null) {
            dUrl = new ArrayList<DUrl>();
        }
        return this.dUrl;
    }

    /**
     * Gets the value of the dCompilatore property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dCompilatore property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDCompilatore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DCompilatore }
     * 
     * 
     */
    public List<DCompilatore> getDCompilatore() {
        if (dCompilatore == null) {
            dCompilatore = new ArrayList<DCompilatore>();
        }
        return this.dCompilatore;
    }

}
