//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 04:50:28 PM CET 
//


package it.beniculturali.sas.catalogo.comparc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.beniculturali.sas.catalogo.vocabolario_area_tematica.DVocTipoAreaTematica;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fk_voc_tipo_area_tematica">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolario-area_tematica}d_voc_tipo_area_tematica"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fkVocTipoAreaTematica"
})
@XmlRootElement(name = "d_comparc_area_tematica")
public class DComparcAreaTematica {

    @XmlElement(name = "fk_voc_tipo_area_tematica", required = true, nillable = true)
    protected DComparcAreaTematica.FkVocTipoAreaTematica fkVocTipoAreaTematica;

    /**
     * Gets the value of the fkVocTipoAreaTematica property.
     * 
     * @return
     *     possible object is
     *     {@link DComparcAreaTematica.FkVocTipoAreaTematica }
     *     
     */
    public DComparcAreaTematica.FkVocTipoAreaTematica getFkVocTipoAreaTematica() {
        return fkVocTipoAreaTematica;
    }

    /**
     * Sets the value of the fkVocTipoAreaTematica property.
     * 
     * @param value
     *     allowed object is
     *     {@link DComparcAreaTematica.FkVocTipoAreaTematica }
     *     
     */
    public void setFkVocTipoAreaTematica(DComparcAreaTematica.FkVocTipoAreaTematica value) {
        this.fkVocTipoAreaTematica = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolario-area_tematica}d_voc_tipo_area_tematica"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocTipoAreaTematica"
    })
    public static class FkVocTipoAreaTematica {

        @XmlElement(name = "d_voc_tipo_area_tematica", namespace = "http://sas.beniculturali.it/catalogo/vocabolario-area_tematica")
        protected DVocTipoAreaTematica dVocTipoAreaTematica;

        /**
         * Gets the value of the dVocTipoAreaTematica property.
         * 
         * @return
         *     possible object is
         *     {@link DVocTipoAreaTematica }
         *     
         */
        public DVocTipoAreaTematica getDVocTipoAreaTematica() {
            return dVocTipoAreaTematica;
        }

        /**
         * Sets the value of the dVocTipoAreaTematica property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocTipoAreaTematica }
         *     
         */
        public void setDVocTipoAreaTematica(DVocTipoAreaTematica value) {
            this.dVocTipoAreaTematica = value;
        }

    }

}
