//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.07 at 10:27:57 AM CET 
//


package it.beniculturali.sas.catalogo.comparc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.beniculturali.sas.catalogo.vocabolari_comparc.DVocTipoDanno;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fk_voc_tipo_danno">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-comparc}d_voc_tipo_danno"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fkVocTipoDanno"
})
@XmlRootElement(name = "d_comparc_danni")
public class DComparcDanni {

    @XmlElement(name = "fk_voc_tipo_danno", required = true)
    protected DComparcDanni.FkVocTipoDanno fkVocTipoDanno;

    /**
     * Gets the value of the fkVocTipoDanno property.
     * 
     * @return
     *     possible object is
     *     {@link DComparcDanni.FkVocTipoDanno }
     *     
     */
    public DComparcDanni.FkVocTipoDanno getFkVocTipoDanno() {
        return fkVocTipoDanno;
    }

    /**
     * Sets the value of the fkVocTipoDanno property.
     * 
     * @param value
     *     allowed object is
     *     {@link DComparcDanni.FkVocTipoDanno }
     *     
     */
    public void setFkVocTipoDanno(DComparcDanni.FkVocTipoDanno value) {
        this.fkVocTipoDanno = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-comparc}d_voc_tipo_danno"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocTipoDanno"
    })
    public static class FkVocTipoDanno {

        @XmlElement(name = "d_voc_tipo_danno", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-comparc")
        protected List<DVocTipoDanno> dVocTipoDanno;

        /**
         * Gets the value of the dVocTipoDanno property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dVocTipoDanno property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDVocTipoDanno().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DVocTipoDanno }
         * 
         * 
         */
        public List<DVocTipoDanno> getDVocTipoDanno() {
            if (dVocTipoDanno == null) {
                dVocTipoDanno = new ArrayList<DVocTipoDanno>();
            }
            return this.dVocTipoDanno;
        }

    }

}
