//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 04:50:28 PM CET 
//


package it.beniculturali.sas.catalogo.comparc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.beniculturali.sas.catalogo.vocabolari_comparc.DVocTipologiaIconografica;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fk_voc_tipologia_iconografica">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-comparc}d_voc_tipologia_iconografica"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="flg_tipo_sigillo_rv">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="R"/>
 *               &lt;enumeration value="V"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fkVocTipologiaIconografica",
    "flgTipoSigilloRv"
})
@XmlRootElement(name = "d_rel_comparc_sig_iconografica")
public class DRelComparcSigIconografica {

    @XmlElement(name = "fk_voc_tipologia_iconografica", required = true)
    protected DRelComparcSigIconografica.FkVocTipologiaIconografica fkVocTipologiaIconografica;
    @XmlElement(name = "flg_tipo_sigillo_rv", required = true, nillable = true)
    protected String flgTipoSigilloRv;

    /**
     * Gets the value of the fkVocTipologiaIconografica property.
     * 
     * @return
     *     possible object is
     *     {@link DRelComparcSigIconografica.FkVocTipologiaIconografica }
     *     
     */
    public DRelComparcSigIconografica.FkVocTipologiaIconografica getFkVocTipologiaIconografica() {
        return fkVocTipologiaIconografica;
    }

    /**
     * Sets the value of the fkVocTipologiaIconografica property.
     * 
     * @param value
     *     allowed object is
     *     {@link DRelComparcSigIconografica.FkVocTipologiaIconografica }
     *     
     */
    public void setFkVocTipologiaIconografica(DRelComparcSigIconografica.FkVocTipologiaIconografica value) {
        this.fkVocTipologiaIconografica = value;
    }

    /**
     * Gets the value of the flgTipoSigilloRv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlgTipoSigilloRv() {
        return flgTipoSigilloRv;
    }

    /**
     * Sets the value of the flgTipoSigilloRv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlgTipoSigilloRv(String value) {
        this.flgTipoSigilloRv = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-comparc}d_voc_tipologia_iconografica"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocTipologiaIconografica"
    })
    public static class FkVocTipologiaIconografica {

        @XmlElement(name = "d_voc_tipologia_iconografica", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-comparc")
        protected DVocTipologiaIconografica dVocTipologiaIconografica;

        /**
         * Gets the value of the dVocTipologiaIconografica property.
         * 
         * @return
         *     possible object is
         *     {@link DVocTipologiaIconografica }
         *     
         */
        public DVocTipologiaIconografica getDVocTipologiaIconografica() {
            return dVocTipologiaIconografica;
        }

        /**
         * Sets the value of the dVocTipologiaIconografica property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocTipologiaIconografica }
         *     
         */
        public void setDVocTipologiaIconografica(DVocTipologiaIconografica value) {
            this.dVocTipologiaIconografica = value;
        }

    }

}
