//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 11:10:43 AM CET 
//


package it.beniculturali.sas.catalogo.fonti;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="group_name">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="IT-ACS"/>
 *               &lt;enumeration value="IT-ACS.1"/>
 *               &lt;enumeration value="IT-ACS.3"/>
 *               &lt;enumeration value="IT-ASAG"/>
 *               &lt;enumeration value="IT-ASAG.1"/>
 *               &lt;enumeration value="IT-ASAG.3"/>
 *               &lt;enumeration value="IT-ASAL"/>
 *               &lt;enumeration value="IT-ASAL.1"/>
 *               &lt;enumeration value="IT-ASAL.3"/>
 *               &lt;enumeration value="IT-ASAN"/>
 *               &lt;enumeration value="IT-ASAN.1"/>
 *               &lt;enumeration value="IT-ASAN.3"/>
 *               &lt;enumeration value="IT-ASAO"/>
 *               &lt;enumeration value="IT-ASAO.1"/>
 *               &lt;enumeration value="IT-ASAO.3"/>
 *               &lt;enumeration value="IT-ASAP"/>
 *               &lt;enumeration value="IT-ASAP.1"/>
 *               &lt;enumeration value="IT-ASAP.3"/>
 *               &lt;enumeration value="IT-ASAQ"/>
 *               &lt;enumeration value="IT-ASAQ.1"/>
 *               &lt;enumeration value="IT-ASAQ.3"/>
 *               &lt;enumeration value="IT-ASAR"/>
 *               &lt;enumeration value="IT-ASAR.1"/>
 *               &lt;enumeration value="IT-ASAR.3"/>
 *               &lt;enumeration value="IT-ASAT"/>
 *               &lt;enumeration value="IT-ASAT.1"/>
 *               &lt;enumeration value="IT-ASAT.3"/>
 *               &lt;enumeration value="IT-ASAV"/>
 *               &lt;enumeration value="IT-ASAV.1"/>
 *               &lt;enumeration value="IT-ASAV.3"/>
 *               &lt;enumeration value="IT-ASBA"/>
 *               &lt;enumeration value="IT-ASBA.1"/>
 *               &lt;enumeration value="IT-ASBA.3"/>
 *               &lt;enumeration value="IT-ASBG"/>
 *               &lt;enumeration value="IT-ASBG.1"/>
 *               &lt;enumeration value="IT-ASBG.2"/>
 *               &lt;enumeration value="IT-ASBG.3"/>
 *               &lt;enumeration value="IT-ASBI"/>
 *               &lt;enumeration value="IT-ASBI.1"/>
 *               &lt;enumeration value="IT-ASBI.3"/>
 *               &lt;enumeration value="IT-ASBL"/>
 *               &lt;enumeration value="IT-ASBL.1"/>
 *               &lt;enumeration value="IT-ASBL.3"/>
 *               &lt;enumeration value="IT-ASBN"/>
 *               &lt;enumeration value="IT-ASBN.1"/>
 *               &lt;enumeration value="IT-ASBN.3"/>
 *               &lt;enumeration value="IT-ASBO"/>
 *               &lt;enumeration value="IT-ASBO.1"/>
 *               &lt;enumeration value="IT-ASBO.2"/>
 *               &lt;enumeration value="IT-ASBO.3"/>
 *               &lt;enumeration value="IT-ASBR"/>
 *               &lt;enumeration value="IT-ASBR.1"/>
 *               &lt;enumeration value="IT-ASBR.2"/>
 *               &lt;enumeration value="IT-ASBR.3"/>
 *               &lt;enumeration value="IT-ASBS"/>
 *               &lt;enumeration value="IT-ASBS.1"/>
 *               &lt;enumeration value="IT-ASBS.3"/>
 *               &lt;enumeration value="IT-ASBT"/>
 *               &lt;enumeration value="IT-ASBT.1"/>
 *               &lt;enumeration value="IT-ASBT.3"/>
 *               &lt;enumeration value="IT-ASBZ"/>
 *               &lt;enumeration value="IT-ASBZ.1"/>
 *               &lt;enumeration value="IT-ASBZ.3"/>
 *               &lt;enumeration value="IT-ASCA"/>
 *               &lt;enumeration value="IT-ASCA.1"/>
 *               &lt;enumeration value="IT-ASCA.3"/>
 *               &lt;enumeration value="IT-ASCB"/>
 *               &lt;enumeration value="IT-ASCB.1"/>
 *               &lt;enumeration value="IT-ASCB.3"/>
 *               &lt;enumeration value="IT-ASCE"/>
 *               &lt;enumeration value="IT-ASCE.1"/>
 *               &lt;enumeration value="IT-ASCE.3"/>
 *               &lt;enumeration value="IT-ASCH"/>
 *               &lt;enumeration value="IT-ASCH.1"/>
 *               &lt;enumeration value="IT-ASCH.3"/>
 *               &lt;enumeration value="IT-ASCI"/>
 *               &lt;enumeration value="IT-ASCI.1"/>
 *               &lt;enumeration value="IT-ASCI.3"/>
 *               &lt;enumeration value="IT-ASCL"/>
 *               &lt;enumeration value="IT-ASCL.1"/>
 *               &lt;enumeration value="IT-ASCL.3"/>
 *               &lt;enumeration value="IT-ASCN"/>
 *               &lt;enumeration value="IT-ASCN.1"/>
 *               &lt;enumeration value="IT-ASCN.3"/>
 *               &lt;enumeration value="IT-ASCO"/>
 *               &lt;enumeration value="IT-ASCO.1"/>
 *               &lt;enumeration value="IT-ASCO.2"/>
 *               &lt;enumeration value="IT-ASCO.3"/>
 *               &lt;enumeration value="IT-ASCR"/>
 *               &lt;enumeration value="IT-ASCR.1"/>
 *               &lt;enumeration value="IT-ASCR.2"/>
 *               &lt;enumeration value="IT-ASCR.3"/>
 *               &lt;enumeration value="IT-ASCS"/>
 *               &lt;enumeration value="IT-ASCS.1"/>
 *               &lt;enumeration value="IT-ASCS.3"/>
 *               &lt;enumeration value="IT-ASCT.1"/>
 *               &lt;enumeration value="IT-ASCT.3"/>
 *               &lt;enumeration value="IT-ASCT\n"/>
 *               &lt;enumeration value="IT-ASCZ"/>
 *               &lt;enumeration value="IT-ASCZ.1"/>
 *               &lt;enumeration value="IT-ASCZ.3"/>
 *               &lt;enumeration value="IT-ASEN"/>
 *               &lt;enumeration value="IT-ASEN.1"/>
 *               &lt;enumeration value="IT-ASEN.3"/>
 *               &lt;enumeration value="IT-ASFC"/>
 *               &lt;enumeration value="IT-ASFC.1"/>
 *               &lt;enumeration value="IT-ASFC.3"/>
 *               &lt;enumeration value="IT-ASFE"/>
 *               &lt;enumeration value="IT-ASFE.1"/>
 *               &lt;enumeration value="IT-ASFE.3"/>
 *               &lt;enumeration value="IT-ASFG"/>
 *               &lt;enumeration value="IT-ASFG.1"/>
 *               &lt;enumeration value="IT-ASFG.3"/>
 *               &lt;enumeration value="IT-ASFI"/>
 *               &lt;enumeration value="IT-ASFI.1"/>
 *               &lt;enumeration value="IT-ASFI.2"/>
 *               &lt;enumeration value="IT-ASFI.3"/>
 *               &lt;enumeration value="IT-ASFM"/>
 *               &lt;enumeration value="IT-ASFM.1"/>
 *               &lt;enumeration value="IT-ASFM.3"/>
 *               &lt;enumeration value="IT-ASFR"/>
 *               &lt;enumeration value="IT-ASFR.1"/>
 *               &lt;enumeration value="IT-ASFR.3"/>
 *               &lt;enumeration value="IT-ASGE"/>
 *               &lt;enumeration value="IT-ASGE.1"/>
 *               &lt;enumeration value="IT-ASGE.3"/>
 *               &lt;enumeration value="IT-ASGO"/>
 *               &lt;enumeration value="IT-ASGO.1"/>
 *               &lt;enumeration value="IT-ASGO.3"/>
 *               &lt;enumeration value="IT-ASGR"/>
 *               &lt;enumeration value="IT-ASGR.1"/>
 *               &lt;enumeration value="IT-ASGR.3"/>
 *               &lt;enumeration value="IT-ASIM"/>
 *               &lt;enumeration value="IT-ASIM.1"/>
 *               &lt;enumeration value="IT-ASIM.3"/>
 *               &lt;enumeration value="IT-ASIS"/>
 *               &lt;enumeration value="IT-ASIS.1"/>
 *               &lt;enumeration value="IT-ASIS.3"/>
 *               &lt;enumeration value="IT-ASKR"/>
 *               &lt;enumeration value="IT-ASKR.1"/>
 *               &lt;enumeration value="IT-ASKR.3"/>
 *               &lt;enumeration value="IT-ASLC"/>
 *               &lt;enumeration value="IT-ASLC.1"/>
 *               &lt;enumeration value="IT-ASLC.3"/>
 *               &lt;enumeration value="IT-ASLE"/>
 *               &lt;enumeration value="IT-ASLE.1"/>
 *               &lt;enumeration value="IT-ASLE.3"/>
 *               &lt;enumeration value="IT-ASLI"/>
 *               &lt;enumeration value="IT-ASLI.1"/>
 *               &lt;enumeration value="IT-ASLI.3"/>
 *               &lt;enumeration value="IT-ASLO"/>
 *               &lt;enumeration value="IT-ASLO.1"/>
 *               &lt;enumeration value="IT-ASLO.3"/>
 *               &lt;enumeration value="IT-ASLT"/>
 *               &lt;enumeration value="IT-ASLT.1"/>
 *               &lt;enumeration value="IT-ASLT.3"/>
 *               &lt;enumeration value="IT-ASLU"/>
 *               &lt;enumeration value="IT-ASLU.1"/>
 *               &lt;enumeration value="IT-ASLU.3"/>
 *               &lt;enumeration value="IT-ASMB"/>
 *               &lt;enumeration value="IT-ASMB.1"/>
 *               &lt;enumeration value="IT-ASMB.3"/>
 *               &lt;enumeration value="IT-ASMC"/>
 *               &lt;enumeration value="IT-ASMC.1"/>
 *               &lt;enumeration value="IT-ASMC.3"/>
 *               &lt;enumeration value="IT-ASME"/>
 *               &lt;enumeration value="IT-ASME.1"/>
 *               &lt;enumeration value="IT-ASME.3"/>
 *               &lt;enumeration value="IT-ASMI"/>
 *               &lt;enumeration value="IT-ASMI.1"/>
 *               &lt;enumeration value="IT-ASMI.2"/>
 *               &lt;enumeration value="IT-ASMI.3"/>
 *               &lt;enumeration value="IT-ASMN"/>
 *               &lt;enumeration value="IT-ASMN.1"/>
 *               &lt;enumeration value="IT-ASMN.3"/>
 *               &lt;enumeration value="IT-ASMO"/>
 *               &lt;enumeration value="IT-ASMO.1"/>
 *               &lt;enumeration value="IT-ASMO.2"/>
 *               &lt;enumeration value="IT-ASMO.3"/>
 *               &lt;enumeration value="IT-ASMS"/>
 *               &lt;enumeration value="IT-ASMS.1"/>
 *               &lt;enumeration value="IT-ASMS.3"/>
 *               &lt;enumeration value="IT-ASMT"/>
 *               &lt;enumeration value="IT-ASMT.1"/>
 *               &lt;enumeration value="IT-ASMT.3"/>
 *               &lt;enumeration value="IT-ASNA"/>
 *               &lt;enumeration value="IT-ASNA.1"/>
 *               &lt;enumeration value="IT-ASNA.2"/>
 *               &lt;enumeration value="IT-ASNA.3"/>
 *               &lt;enumeration value="IT-ASNO"/>
 *               &lt;enumeration value="IT-ASNO.1"/>
 *               &lt;enumeration value="IT-ASNO.3"/>
 *               &lt;enumeration value="IT-ASNU"/>
 *               &lt;enumeration value="IT-ASNU.1"/>
 *               &lt;enumeration value="IT-ASNU.3"/>
 *               &lt;enumeration value="IT-ASOG"/>
 *               &lt;enumeration value="IT-ASOG.1"/>
 *               &lt;enumeration value="IT-ASOG.3"/>
 *               &lt;enumeration value="IT-ASOR"/>
 *               &lt;enumeration value="IT-ASOR.1"/>
 *               &lt;enumeration value="IT-ASOR.3"/>
 *               &lt;enumeration value="IT-ASOT"/>
 *               &lt;enumeration value="IT-ASOT.1"/>
 *               &lt;enumeration value="IT-ASOT.3"/>
 *               &lt;enumeration value="IT-ASPA"/>
 *               &lt;enumeration value="IT-ASPA.1"/>
 *               &lt;enumeration value="IT-ASPA.2"/>
 *               &lt;enumeration value="IT-ASPA.3"/>
 *               &lt;enumeration value="IT-ASPC"/>
 *               &lt;enumeration value="IT-ASPC.1"/>
 *               &lt;enumeration value="IT-ASPC.3"/>
 *               &lt;enumeration value="IT-ASPD"/>
 *               &lt;enumeration value="IT-ASPD.1"/>
 *               &lt;enumeration value="IT-ASPD.3"/>
 *               &lt;enumeration value="IT-ASPE"/>
 *               &lt;enumeration value="IT-ASPE.1"/>
 *               &lt;enumeration value="IT-ASPE.3"/>
 *               &lt;enumeration value="IT-ASPG"/>
 *               &lt;enumeration value="IT-ASPG.1"/>
 *               &lt;enumeration value="IT-ASPG.2"/>
 *               &lt;enumeration value="IT-ASPG.3"/>
 *               &lt;enumeration value="IT-ASPI"/>
 *               &lt;enumeration value="IT-ASPI.1"/>
 *               &lt;enumeration value="IT-ASPI.3"/>
 *               &lt;enumeration value="IT-ASPN"/>
 *               &lt;enumeration value="IT-ASPN.1"/>
 *               &lt;enumeration value="IT-ASPN.3"/>
 *               &lt;enumeration value="IT-ASPO"/>
 *               &lt;enumeration value="IT-ASPO.1"/>
 *               &lt;enumeration value="IT-ASPO.3"/>
 *               &lt;enumeration value="IT-ASPR"/>
 *               &lt;enumeration value="IT-ASPR.1"/>
 *               &lt;enumeration value="IT-ASPR.3"/>
 *               &lt;enumeration value="IT-ASPT"/>
 *               &lt;enumeration value="IT-ASPT.1"/>
 *               &lt;enumeration value="IT-ASPT.3"/>
 *               &lt;enumeration value="IT-ASPU"/>
 *               &lt;enumeration value="IT-ASPU.1"/>
 *               &lt;enumeration value="IT-ASPU.3"/>
 *               &lt;enumeration value="IT-ASPV"/>
 *               &lt;enumeration value="IT-ASPV.1"/>
 *               &lt;enumeration value="IT-ASPV.3"/>
 *               &lt;enumeration value="IT-ASPZ"/>
 *               &lt;enumeration value="IT-ASPZ.1"/>
 *               &lt;enumeration value="IT-ASPZ.3"/>
 *               &lt;enumeration value="IT-ASRA"/>
 *               &lt;enumeration value="IT-ASRA.1"/>
 *               &lt;enumeration value="IT-ASRA.3"/>
 *               &lt;enumeration value="IT-ASRC"/>
 *               &lt;enumeration value="IT-ASRC.1"/>
 *               &lt;enumeration value="IT-ASRC.3"/>
 *               &lt;enumeration value="IT-ASRE"/>
 *               &lt;enumeration value="IT-ASRE.1"/>
 *               &lt;enumeration value="IT-ASRE.3"/>
 *               &lt;enumeration value="IT-ASRG"/>
 *               &lt;enumeration value="IT-ASRG.1"/>
 *               &lt;enumeration value="IT-ASRG.3"/>
 *               &lt;enumeration value="IT-ASRI"/>
 *               &lt;enumeration value="IT-ASRI.1"/>
 *               &lt;enumeration value="IT-ASRI.3"/>
 *               &lt;enumeration value="IT-ASRM"/>
 *               &lt;enumeration value="IT-ASRM.1"/>
 *               &lt;enumeration value="IT-ASRM.3"/>
 *               &lt;enumeration value="IT-ASRN"/>
 *               &lt;enumeration value="IT-ASRN.1"/>
 *               &lt;enumeration value="IT-ASRN.3"/>
 *               &lt;enumeration value="IT-ASRO"/>
 *               &lt;enumeration value="IT-ASRO.1"/>
 *               &lt;enumeration value="IT-ASRO.3"/>
 *               &lt;enumeration value="IT-ASSA"/>
 *               &lt;enumeration value="IT-ASSA.1"/>
 *               &lt;enumeration value="IT-ASSA.3"/>
 *               &lt;enumeration value="IT-ASSI"/>
 *               &lt;enumeration value="IT-ASSI.1"/>
 *               &lt;enumeration value="IT-ASSI.3"/>
 *               &lt;enumeration value="IT-ASSO"/>
 *               &lt;enumeration value="IT-ASSO.1"/>
 *               &lt;enumeration value="IT-ASSO.2"/>
 *               &lt;enumeration value="IT-ASSO.3"/>
 *               &lt;enumeration value="IT-ASSP"/>
 *               &lt;enumeration value="IT-ASSP.1"/>
 *               &lt;enumeration value="IT-ASSP.3"/>
 *               &lt;enumeration value="IT-ASSR"/>
 *               &lt;enumeration value="IT-ASSR.1"/>
 *               &lt;enumeration value="IT-ASSR.3"/>
 *               &lt;enumeration value="IT-ASSS"/>
 *               &lt;enumeration value="IT-ASSS.1"/>
 *               &lt;enumeration value="IT-ASSS.3"/>
 *               &lt;enumeration value="IT-ASSV"/>
 *               &lt;enumeration value="IT-ASSV.1"/>
 *               &lt;enumeration value="IT-ASSV.3"/>
 *               &lt;enumeration value="IT-ASTA"/>
 *               &lt;enumeration value="IT-ASTA.1"/>
 *               &lt;enumeration value="IT-ASTA.3"/>
 *               &lt;enumeration value="IT-ASTE"/>
 *               &lt;enumeration value="IT-ASTE.1"/>
 *               &lt;enumeration value="IT-ASTE.3"/>
 *               &lt;enumeration value="IT-ASTN"/>
 *               &lt;enumeration value="IT-ASTN.1"/>
 *               &lt;enumeration value="IT-ASTN.3"/>
 *               &lt;enumeration value="IT-ASTO"/>
 *               &lt;enumeration value="IT-ASTO.1"/>
 *               &lt;enumeration value="IT-ASTO.3"/>
 *               &lt;enumeration value="IT-ASTP"/>
 *               &lt;enumeration value="IT-ASTP.1"/>
 *               &lt;enumeration value="IT-ASTP.3"/>
 *               &lt;enumeration value="IT-ASTR"/>
 *               &lt;enumeration value="IT-ASTR.1"/>
 *               &lt;enumeration value="IT-ASTR.3"/>
 *               &lt;enumeration value="IT-ASTS"/>
 *               &lt;enumeration value="IT-ASTS.1"/>
 *               &lt;enumeration value="IT-ASTS.3"/>
 *               &lt;enumeration value="IT-ASTV"/>
 *               &lt;enumeration value="IT-ASTV.1"/>
 *               &lt;enumeration value="IT-ASTV.3"/>
 *               &lt;enumeration value="IT-ASUD"/>
 *               &lt;enumeration value="IT-ASUD.1"/>
 *               &lt;enumeration value="IT-ASUD.3"/>
 *               &lt;enumeration value="IT-ASVA"/>
 *               &lt;enumeration value="IT-ASVA.1"/>
 *               &lt;enumeration value="IT-ASVA.2"/>
 *               &lt;enumeration value="IT-ASVA.3"/>
 *               &lt;enumeration value="IT-ASVB"/>
 *               &lt;enumeration value="IT-ASVB.1"/>
 *               &lt;enumeration value="IT-ASVB.3"/>
 *               &lt;enumeration value="IT-ASVC"/>
 *               &lt;enumeration value="IT-ASVC.1"/>
 *               &lt;enumeration value="IT-ASVC.3"/>
 *               &lt;enumeration value="IT-ASVE"/>
 *               &lt;enumeration value="IT-ASVE.1"/>
 *               &lt;enumeration value="IT-ASVE.2"/>
 *               &lt;enumeration value="IT-ASVE.3"/>
 *               &lt;enumeration value="IT-ASVI"/>
 *               &lt;enumeration value="IT-ASVI.1"/>
 *               &lt;enumeration value="IT-ASVI.3"/>
 *               &lt;enumeration value="IT-ASVR"/>
 *               &lt;enumeration value="IT-ASVR.1"/>
 *               &lt;enumeration value="IT-ASVR.3"/>
 *               &lt;enumeration value="IT-ASVS"/>
 *               &lt;enumeration value="IT-ASVS.1"/>
 *               &lt;enumeration value="IT-ASVS.3"/>
 *               &lt;enumeration value="IT-ASVT"/>
 *               &lt;enumeration value="IT-ASVT.1"/>
 *               &lt;enumeration value="IT-ASVT.3"/>
 *               &lt;enumeration value="IT-ASVV"/>
 *               &lt;enumeration value="IT-ASVV.1"/>
 *               &lt;enumeration value="IT-ASVV.3"/>
 *               &lt;enumeration value="IT-ER-BC"/>
 *               &lt;enumeration value="IT-ER-IBC"/>
 *               &lt;enumeration value="ITASAG"/>
 *               &lt;enumeration value="ITASAL"/>
 *               &lt;enumeration value="ITASAN"/>
 *               &lt;enumeration value="ITASBG"/>
 *               &lt;enumeration value="ITASCT"/>
 *               &lt;enumeration value="ITASCT_SEZ_CALTAGIRONE"/>
 *               &lt;enumeration value="ITASLT"/>
 *               &lt;enumeration value="ITASNA"/>
 *               &lt;enumeration value="ITASPA"/>
 *               &lt;enumeration value="ITASRI"/>
 *               &lt;enumeration value="ITASSI"/>
 *               &lt;enumeration value="ITASVT"/>
 *               &lt;enumeration value="ITSASFABRI"/>
 *               &lt;enumeration value="LBC"/>
 *               &lt;enumeration value="PRCT"/>
 *               &lt;enumeration value="PREPCT"/>
 *               &lt;enumeration value="SAAN"/>
 *               &lt;enumeration value="SAAQ"/>
 *               &lt;enumeration value="SABA"/>
 *               &lt;enumeration value="SABO"/>
 *               &lt;enumeration value="SACA"/>
 *               &lt;enumeration value="SACB"/>
 *               &lt;enumeration value="SAFI"/>
 *               &lt;enumeration value="SAGE"/>
 *               &lt;enumeration value="SAMI"/>
 *               &lt;enumeration value="SANA"/>
 *               &lt;enumeration value="SAPA"/>
 *               &lt;enumeration value="SAPG"/>
 *               &lt;enumeration value="SAPZ"/>
 *               &lt;enumeration value="SARC"/>
 *               &lt;enumeration value="SARM"/>
 *               &lt;enumeration value="SATN"/>
 *               &lt;enumeration value="SATO"/>
 *               &lt;enumeration value="SATS"/>
 *               &lt;enumeration value="SAVE"/>
 *               &lt;enumeration value="SEZIONE_DISTACCATA_DI_SCIACCA"/>
 *               &lt;enumeration value="SIASBO"/>
 *               &lt;enumeration value="SIASFI"/>
 *               &lt;enumeration value="SIASNA"/>
 *               &lt;enumeration value="SIASPG"/>
 *               &lt;enumeration value="SIASVE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupName"
})
@XmlRootElement(name = "prof_group")
public class ProfGroup {

    @XmlElement(name = "group_name", required = true)
    protected String groupName;

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

}
