//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.11 at 06:42:47 PM CET 
//


package it.beniculturali.sas.catalogo.vocabolari_strumenti;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.beniculturali.sas.catalogo.vocabolari_strumenti package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.beniculturali.sas.catalogo.vocabolari_strumenti
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DVocTipoStrricOrganizzazione }
     * 
     */
    public DVocTipoStrricOrganizzazione createDVocTipoStrricOrganizzazione() {
        return new DVocTipoStrricOrganizzazione();
    }

    /**
     * Create an instance of {@link DVocTipoStrricRicerca }
     * 
     */
    public DVocTipoStrricRicerca createDVocTipoStrricRicerca() {
        return new DVocTipoStrricRicerca();
    }

    /**
     * Create an instance of {@link DVocQualificaStrric }
     * 
     */
    public DVocQualificaStrric createDVocQualificaStrric() {
        return new DVocQualificaStrric();
    }

    /**
     * Create an instance of {@link DVocTipoSuppStrric }
     * 
     */
    public DVocTipoSuppStrric createDVocTipoSuppStrric() {
        return new DVocTipoSuppStrric();
    }

}
