//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.25 at 03:07:39 PM CET 
//


package it.beniculturali.sas.catalogo.vocabolari_comparc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.beniculturali.sas.catalogo.vocabolari_comparc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.beniculturali.sas.catalogo.vocabolari_comparc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DVocTipoComparc }
     * 
     */
    public DVocTipoComparc createDVocTipoComparc() {
        return new DVocTipoComparc();
    }

    /**
     * Create an instance of {@link DVocRuoloAttoreCarteggio }
     * 
     */
    public DVocRuoloAttoreCarteggio createDVocRuoloAttoreCarteggio() {
        return new DVocRuoloAttoreCarteggio();
    }

    /**
     * Create an instance of {@link DVocNaturaColl }
     * 
     */
    public DVocNaturaColl createDVocNaturaColl() {
        return new DVocNaturaColl();
    }

    /**
     * Create an instance of {@link DVocMateriaSigillo }
     * 
     */
    public DVocMateriaSigillo createDVocMateriaSigillo() {
        return new DVocMateriaSigillo();
    }

    /**
     * Create an instance of {@link DVocTipoNumerazione }
     * 
     */
    public DVocTipoNumerazione createDVocTipoNumerazione() {
        return new DVocTipoNumerazione();
    }

    /**
     * Create an instance of {@link DVocNaturaSigillo }
     * 
     */
    public DVocNaturaSigillo createDVocNaturaSigillo() {
        return new DVocNaturaSigillo();
    }

    /**
     * Create an instance of {@link DVocTipoForma }
     * 
     */
    public DVocTipoForma createDVocTipoForma() {
        return new DVocTipoForma();
    }

    /**
     * Create an instance of {@link DVocTipologiaIconografica }
     * 
     */
    public DVocTipologiaIconografica createDVocTipologiaIconografica() {
        return new DVocTipologiaIconografica();
    }

    /**
     * Create an instance of {@link DVocTipoOggettiCons }
     * 
     */
    public DVocTipoOggettiCons createDVocTipoOggettiCons() {
        return new DVocTipoOggettiCons();
    }

    /**
     * Create an instance of {@link DVocStatoInventariazione }
     * 
     */
    public DVocStatoInventariazione createDVocStatoInventariazione() {
        return new DVocStatoInventariazione();
    }

    /**
     * Create an instance of {@link DVocTipoLettera }
     * 
     */
    public DVocTipoLettera createDVocTipoLettera() {
        return new DVocTipoLettera();
    }

    /**
     * Create an instance of {@link DVocTipologiaConservatore }
     * 
     */
    public DVocTipologiaConservatore createDVocTipologiaConservatore() {
        return new DVocTipologiaConservatore();
    }

    /**
     * Create an instance of {@link DVocTipoSupporto }
     * 
     */
    public DVocTipoSupporto createDVocTipoSupporto() {
        return new DVocTipoSupporto();
    }

    /**
     * Create an instance of {@link DVocQualificaCommittente }
     * 
     */
    public DVocQualificaCommittente createDVocQualificaCommittente() {
        return new DVocQualificaCommittente();
    }

    /**
     * Create an instance of {@link DVocQualificaAttoreCarteggio }
     * 
     */
    public DVocQualificaAttoreCarteggio createDVocQualificaAttoreCarteggio() {
        return new DVocQualificaAttoreCarteggio();
    }

    /**
     * Create an instance of {@link DVocSottotipoUa }
     * 
     */
    public DVocSottotipoUa createDVocSottotipoUa() {
        return new DVocSottotipoUa();
    }

    /**
     * Create an instance of {@link DVocQualitaImpressione }
     * 
     */
    public DVocQualitaImpressione createDVocQualitaImpressione() {
        return new DVocQualitaImpressione();
    }

    /**
     * Create an instance of {@link DVocStatoConservazione }
     * 
     */
    public DVocStatoConservazione createDVocStatoConservazione() {
        return new DVocStatoConservazione();
    }

    /**
     * Create an instance of {@link DVocTipoFormato }
     * 
     */
    public DVocTipoFormato createDVocTipoFormato() {
        return new DVocTipoFormato();
    }

    /**
     * Create an instance of {@link DVocTipoSupportoCart }
     * 
     */
    public DVocTipoSupportoCart createDVocTipoSupportoCart() {
        return new DVocTipoSupportoCart();
    }

    /**
     * Create an instance of {@link DVocProcGrafico }
     * 
     */
    public DVocProcGrafico createDVocProcGrafico() {
        return new DVocProcGrafico();
    }

    /**
     * Create an instance of {@link DVocTipoRappr }
     * 
     */
    public DVocTipoRappr createDVocTipoRappr() {
        return new DVocTipoRappr();
    }

    /**
     * Create an instance of {@link DVocStatoOrdinamento }
     * 
     */
    public DVocStatoOrdinamento createDVocStatoOrdinamento() {
        return new DVocStatoOrdinamento();
    }

    /**
     * Create an instance of {@link DVocStatoDescrizione }
     * 
     */
    public DVocStatoDescrizione createDVocStatoDescrizione() {
        return new DVocStatoDescrizione();
    }

    /**
     * Create an instance of {@link DVocTipoUd }
     * 
     */
    public DVocTipoUd createDVocTipoUd() {
        return new DVocTipoUd();
    }

    /**
     * Create an instance of {@link DVocMediazioniGrafiche }
     * 
     */
    public DVocMediazioniGrafiche createDVocMediazioniGrafiche() {
        return new DVocMediazioniGrafiche();
    }

    /**
     * Create an instance of {@link DVocTipoUa }
     * 
     */
    public DVocTipoUa createDVocTipoUa() {
        return new DVocTipoUa();
    }

    /**
     * Create an instance of {@link DVocTipoProiezione }
     * 
     */
    public DVocTipoProiezione createDVocTipoProiezione() {
        return new DVocTipoProiezione();
    }

    /**
     * Create an instance of {@link DVocTipoLegatura }
     * 
     */
    public DVocTipoLegatura createDVocTipoLegatura() {
        return new DVocTipoLegatura();
    }

    /**
     * Create an instance of {@link DVocTipoSupportoPerg }
     * 
     */
    public DVocTipoSupportoPerg createDVocTipoSupportoPerg() {
        return new DVocTipoSupportoPerg();
    }

    /**
     * Create an instance of {@link DVocTipoAcquisizione }
     * 
     */
    public DVocTipoAcquisizione createDVocTipoAcquisizione() {
        return new DVocTipoAcquisizione();
    }

    /**
     * Create an instance of {@link DVocQualitaScheda }
     * 
     */
    public DVocQualitaScheda createDVocQualitaScheda() {
        return new DVocQualitaScheda();
    }

    /**
     * Create an instance of {@link DVocTipoDanno }
     * 
     */
    public DVocTipoDanno createDVocTipoDanno() {
        return new DVocTipoDanno();
    }

    /**
     * Create an instance of {@link DVocTipoRuoloTitolare }
     * 
     */
    public DVocTipoRuoloTitolare createDVocTipoRuoloTitolare() {
        return new DVocTipoRuoloTitolare();
    }

    /**
     * Create an instance of {@link DVocColoreSigillo }
     * 
     */
    public DVocColoreSigillo createDVocColoreSigillo() {
        return new DVocColoreSigillo();
    }

    /**
     * Create an instance of {@link DVocModoApposizione }
     * 
     */
    public DVocModoApposizione createDVocModoApposizione() {
        return new DVocModoApposizione();
    }

    /**
     * Create an instance of {@link DVocTipoCarteggio }
     * 
     */
    public DVocTipoCarteggio createDVocTipoCarteggio() {
        return new DVocTipoCarteggio();
    }

    /**
     * Create an instance of {@link DVocRapportoDocumento }
     * 
     */
    public DVocRapportoDocumento createDVocRapportoDocumento() {
        return new DVocRapportoDocumento();
    }

    /**
     * Create an instance of {@link DVocModalitaAcq }
     * 
     */
    public DVocModalitaAcq createDVocModalitaAcq() {
        return new DVocModalitaAcq();
    }

    /**
     * Create an instance of {@link DVocFormaSigillo }
     * 
     */
    public DVocFormaSigillo createDVocFormaSigillo() {
        return new DVocFormaSigillo();
    }

    /**
     * Create an instance of {@link DVocTipoMateriale }
     * 
     */
    public DVocTipoMateriale createDVocTipoMateriale() {
        return new DVocTipoMateriale();
    }

    /**
     * Create an instance of {@link DVocTipologiaDiplGiuridica }
     * 
     */
    public DVocTipologiaDiplGiuridica createDVocTipologiaDiplGiuridica() {
        return new DVocTipologiaDiplGiuridica();
    }

    /**
     * Create an instance of {@link DVocTipoTraditio }
     * 
     */
    public DVocTipoTraditio createDVocTipoTraditio() {
        return new DVocTipoTraditio();
    }

}
