//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 11:10:43 AM CET 
//


package it.beniculturali.sas.catalogo.comparc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text_luogo_edizione">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="1024"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_data_edizione" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textLuogoEdizione",
    "textDataEdizione"
})
@XmlRootElement(name = "d_comparc_cartografie_a_stampa")
public class DComparcCartografieAStampa {

    @XmlElement(name = "text_luogo_edizione", required = true)
    protected String textLuogoEdizione;
    @XmlElementRef(name = "text_data_edizione", namespace = "http://sas.beniculturali.it/catalogo/comparc", type = JAXBElement.class, required = false)
    protected JAXBElement<String> textDataEdizione;

    /**
     * Gets the value of the textLuogoEdizione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLuogoEdizione() {
        return textLuogoEdizione;
    }

    /**
     * Sets the value of the textLuogoEdizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLuogoEdizione(String value) {
        this.textLuogoEdizione = value;
    }

    /**
     * Gets the value of the textDataEdizione property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextDataEdizione() {
        return textDataEdizione;
    }

    /**
     * Sets the value of the textDataEdizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextDataEdizione(JAXBElement<String> value) {
        this.textDataEdizione = value;
    }

}
