//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.18 at 04:50:28 PM CET 
//


package it.beniculturali.sas.catalogo.sogp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import it.beniculturali.sas.catalogo.vocabolari_sogp.DVocTipoCodice;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="text_altro_codice">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fk_voc_tipo_codice">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogp}d_voc_tipo_codice"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="text_luogo_emissione">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="256"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_autorita_emittente">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="256"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="text_data_emissione" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="256"/>
 *               &lt;pattern value="\p{Nd}{4}-\p{Nd}{2}-\p{Nd}{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textAltroCodice",
    "fkVocTipoCodice",
    "textLuogoEmissione",
    "textAutoritaEmittente",
    "textDataEmissione"
})
@XmlRootElement(name = "d_sogp_altri_codici")
public class DSogpAltriCodici {

    @XmlElement(name = "text_altro_codice", required = true, nillable = true)
    protected String textAltroCodice;
    @XmlElement(name = "fk_voc_tipo_codice", required = true, nillable = true)
    protected DSogpAltriCodici.FkVocTipoCodice fkVocTipoCodice;
    @XmlElement(name = "text_luogo_emissione", required = true, nillable = true)
    protected String textLuogoEmissione;
    @XmlElement(name = "text_autorita_emittente", required = true, nillable = true)
    protected String textAutoritaEmittente;
    @XmlElementRef(name = "text_data_emissione", namespace = "http://sas.beniculturali.it/catalogo/sogp", type = JAXBElement.class)
    protected JAXBElement<String> textDataEmissione;

    /**
     * Gets the value of the textAltroCodice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextAltroCodice() {
        return textAltroCodice;
    }

    /**
     * Sets the value of the textAltroCodice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextAltroCodice(String value) {
        this.textAltroCodice = value;
    }

    /**
     * Gets the value of the fkVocTipoCodice property.
     * 
     * @return
     *     possible object is
     *     {@link DSogpAltriCodici.FkVocTipoCodice }
     *     
     */
    public DSogpAltriCodici.FkVocTipoCodice getFkVocTipoCodice() {
        return fkVocTipoCodice;
    }

    /**
     * Sets the value of the fkVocTipoCodice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSogpAltriCodici.FkVocTipoCodice }
     *     
     */
    public void setFkVocTipoCodice(DSogpAltriCodici.FkVocTipoCodice value) {
        this.fkVocTipoCodice = value;
    }

    /**
     * Gets the value of the textLuogoEmissione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLuogoEmissione() {
        return textLuogoEmissione;
    }

    /**
     * Sets the value of the textLuogoEmissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLuogoEmissione(String value) {
        this.textLuogoEmissione = value;
    }

    /**
     * Gets the value of the textAutoritaEmittente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextAutoritaEmittente() {
        return textAutoritaEmittente;
    }

    /**
     * Sets the value of the textAutoritaEmittente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextAutoritaEmittente(String value) {
        this.textAutoritaEmittente = value;
    }

    /**
     * Gets the value of the textDataEmissione property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTextDataEmissione() {
        return textDataEmissione;
    }

    /**
     * Sets the value of the textDataEmissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTextDataEmissione(JAXBElement<String> value) {
        this.textDataEmissione = ((JAXBElement<String> ) value);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://sas.beniculturali.it/catalogo/vocabolari-sogp}d_voc_tipo_codice"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dVocTipoCodice"
    })
    public static class FkVocTipoCodice {

        @XmlElement(name = "d_voc_tipo_codice", namespace = "http://sas.beniculturali.it/catalogo/vocabolari-sogp")
        protected DVocTipoCodice dVocTipoCodice;

        /**
         * Gets the value of the dVocTipoCodice property.
         * 
         * @return
         *     possible object is
         *     {@link DVocTipoCodice }
         *     
         */
        public DVocTipoCodice getDVocTipoCodice() {
            return dVocTipoCodice;
        }

        /**
         * Sets the value of the dVocTipoCodice property.
         * 
         * @param value
         *     allowed object is
         *     {@link DVocTipoCodice }
         *     
         */
        public void setDVocTipoCodice(DVocTipoCodice value) {
            this.dVocTipoCodice = value;
        }

    }

}
